# Generated by Django 5.2.8 on 2026-10-05 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('folio', '0003_folio_note_tending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('writing', 'Writing')], default='writing', max_length=20)),
                ('grammar', models.CharField(help_text='Registry key (e.g. "fiction_v1") resolved against storyboard/grammars.py -- not a Contour shape.', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('head', models.JSONField(blank=True, help_text='Optional rich body (TipTap/ProseMirror) describing the whole Storyboard.', null=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('locked', models.BooleanField(default=False, help_text='Set by a domain companion later (e.g. Issue publication). Unused by Writing for now.')),
                ('created_by', models.ForeignKey(help_text='Real owner FK -- not derived from the optional folio link.', on_delete=django.db.models.deletion.CASCADE, related_name='created_storyboards', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(blank=True, help_text="Optional -- this Storyboard draws from that Folio's FolioNotes, doesn't own them.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storyboards', to='folio.folio')),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryboardItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Ordering among siblings -- canonical authored order. Changing it changes the work.')),
                ('level', models.CharField(help_text='Which grammar level this item occupies (e.g. "part"/"chapter"/"scene" for fiction_v1). Validated against the storyboard\'s grammar at the service layer, not hardcoded here.', max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('reference_object_id', models.UUIDField(blank=True, null=True)),
                ('head', models.JSONField(blank=True, help_text='Optional rich body (e.g. Chapter synopsis, section introduction).', null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storyboard.storyboarditem')),
                ('reference_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storyboard.storyboard')),
            ],
            options={
                'ordering': ['rank'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='storyboard',
            index=models.Index(fields=['created_by'], name='storyboard__created_3b1dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboard',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='storyboard__sponsor_f8e19e_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboarditem',
            index=models.Index(fields=['storyboard', 'parent', 'rank'], name='storyboard__storybo_c6a548_idx'),
        ),
        migrations.AddIndex(
            model_name='storyboarditem',
            index=models.Index(fields=['reference_content_type', 'reference_object_id'], name='storyboard__referen_60bc92_idx'),
        ),
    ]
