# Generated by Django 5.2.8 on 2026-10-06 18:28

import django.db.models.deletion
from django.db import migrations, models


def copy_folio_links(apps, schema_editor):
    Storyboard = apps.get_model('storyboard', 'Storyboard')
    StoryboardFolio = apps.get_model('storyboard', 'StoryboardFolio')
    StoryboardFolio.objects.bulk_create([
        StoryboardFolio(storyboard_id=storyboard.id, folio_id=storyboard.folio_id)
        for storyboard in Storyboard.objects.exclude(folio_id__isnull=True).iterator()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_folio_note_tending'),
        ('storyboard', '0002_surfacestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryboardFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folio.folio')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboard.storyboard')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storyboard',
            name='folios',
            field=models.ManyToManyField(blank=True, related_name='storyboards', through='storyboard.StoryboardFolio', to='folio.folio'),
        ),
        migrations.AddConstraint(
            model_name='storyboardfolio',
            constraint=models.UniqueConstraint(fields=('storyboard', 'folio'), name='unique_storyboard_folio'),
        ),
        migrations.RunPython(copy_folio_links, migrations.RunPython.noop),
        migrations.RemoveField(model_name='storyboard', name='folio'),
    ]
