# Generated by Django 5.2.8 on 2026-10-06 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storyboard', '0003_remove_storyboard_folio_storyboardfolio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('sponsor_object_id', models.UUIDField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('kind', models.CharField(max_length=40)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='storyboard.entity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='storyboard.storyboarditem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryboardItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('target_object_id', models.UUIDField()),
                ('kind', models.CharField(max_length=40)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='storyboard.storyboarditem')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='storyboard__sponsor_d74b60_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('item', 'entity', 'kind'), name='unique_item_entity_kind'),
        ),
        migrations.AddIndex(
            model_name='storyboarditemlink',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='storyboard__target__528e09_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyboarditemlink',
            constraint=models.UniqueConstraint(fields=('item', 'target_content_type', 'target_object_id', 'kind'), name='unique_storyboard_item_link'),
        ),
    ]
