# Generated by Django 5.2.8 on 2026-01-05 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProfileConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(db_index=True, help_text='Profile identifier: event, writing, course, etc.', max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('publish_safety_class', models.CharField(choices=[('psc_0', 'PSC-0 (Draft Only)'), ('psc_1', 'PSC-1 (Conditional Publish)'), ('psc_2', 'PSC-2 (Auto-Publish)')], default='psc_0', help_text='Publish behavior for this profile', max_length=10)),
                ('field_risk_rules', models.JSONField(blank=True, default=dict, help_text="Field → FRC mapping, e.g. {'title': 'frc_1', 'body': 'frc_2'}")),
                ('validation_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for AST validation')),
                ('required_fields', models.JSONField(blank=True, default=list, help_text='List of required field names')),
                ('is_enabled', models.BooleanField(default=True, help_text='Feature flag: enable Workbench for this profile')),
            ],
            options={
                'verbose_name': 'Content Profile Config',
                'verbose_name_plural': 'Content Profile Configs',
                'db_table': 'fundamentals_content_profile_config',
                'ordering': ['profile_name'],
            },
        ),
        migrations.CreateModel(
            name='MillDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', help_text='Display name for author', max_length=255)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('ready_to_promote', 'Ready to Promote'), ('promoted', 'Promoted'), ('archived', 'Archived')], db_index=True, default='candidate', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, help_text='Last time status changed')),
                ('content_profile', models.CharField(db_index=True, help_text='Content type: event, writing, course, etc.', max_length=50)),
                ('grist_body', models.TextField(blank=True, default='', help_text='Human-editable text content (required at editing time)')),
                ('ast', models.JSONField(blank=True, help_text='Machine-parseable structure (required for promotion)', null=True)),
                ('ast_generation_error', models.TextField(blank=True, default='', help_text='Error message if AST generation failed')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(blank=True, db_index=True, default='', help_text='Origin: stackroom, concord, gristmill, copydesk, in-editor, manual', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', help_text='Source-specific identifier (artifact_id, recording_id, etc.)', max_length=255)),
                ('provenance_bundle', models.JSONField(blank=True, default=dict, help_text='Complete provenance chain (source refs, content hashes, etc.)')),
                ('canonical_object_id', models.UUIDField(blank=True, help_text='ID of canonical object (if editing existing content)', null=True)),
                ('canonical_version', models.IntegerField(blank=True, help_text='Base version for optimistic concurrency (detect stale edits)', null=True)),
                ('validation_state', models.JSONField(blank=True, default=dict, help_text='Current validation errors/warnings')),
                ('validation_last_run', models.DateTimeField(blank=True, help_text='Last time validation ran', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='True if passes hard validation (can promote)')),
                ('promoted_at', models.DateTimeField(blank=True, help_text='When this draft was promoted to canonical', null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When this draft was archived', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp (recoverable)', null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_milldrafts', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, help_text='Original author (may differ from submitted_by)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_milldrafts', to=settings.AUTH_USER_MODEL)),
                ('canonical_content_type', models.ForeignKey(blank=True, help_text='Type of canonical object this draft targets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milldraft_instances', to='contenttypes.contenttype')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_milldrafts', to=settings.AUTH_USER_MODEL)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_milldrafts', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_milldrafts', to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who created this MillDraft record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_milldrafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MillDraft',
                'verbose_name_plural': 'MillDrafts',
                'db_table': 'fundamentals_milldraft',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'status'], name='fundamental_sponsor_71520d_idx'), models.Index(fields=['sponsor_content_type', 'sponsor_object_id', '-created_at'], name='fundamental_sponsor_ca3731_idx'), models.Index(fields=['content_profile', 'status'], name='fundamental_content_39e4a6_idx'), models.Index(fields=['source_type', '-created_at'], name='fundamental_source__dd7521_idx'), models.Index(fields=['canonical_content_type', 'canonical_object_id'], name='fundamental_canonic_db6f6a_idx'), models.Index(fields=['author', '-created_at'], name='fundamental_author__69eef0_idx'), models.Index(fields=['submitted_by', '-created_at'], name='fundamental_submitt_07df50_idx'), models.Index(fields=['status', '-created_at'], name='fundamental_status_24bf78_idx'), models.Index(fields=['is_valid', 'status'], name='fundamental_is_vali_7ad73b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('sponsor_content_type', None), _negated=True), models.Q(('sponsor_object_id', None), _negated=True)), name='milldraft_sponsor_required')],
            },
        ),
    ]
