# Generated by Django 5.2.8 on 2026-03-20 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundamentals', '0002_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MillDraftSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('stackroom', 'Stackroom'), ('concord', 'Concord'), ('gristmill', 'Grist Mill'), ('copydesk', 'Copy Desk'), ('in_editor', 'In-Editor (Inkwell / Beryl)'), ('manual', 'Manual')], db_index=True, help_text='Which source system produced this suggestion', max_length=20)),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', help_text='ID in the source system (artifact_id, recording_id, session_id, etc.)', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full raw payload from the source connector (preserved for provenance)')),
                ('score', models.FloatField(blank=True, help_text='Relevance / confidence score from the source system (0.0–1.0)', null=True)),
                ('accepted', models.BooleanField(default=False, help_text='True if this suggestion was accepted into the active draft')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When this suggestion was accepted', null=True)),
                ('accepted_by', models.ForeignKey(blank=True, help_text='User who accepted this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_suggestions', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(help_text='The MillDraft this suggestion contributed to', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='fundamentals.milldraft')),
            ],
            options={
                'verbose_name': 'MillDraft Suggestion',
                'verbose_name_plural': 'MillDraft Suggestions',
                'db_table': 'fundamentals_milldraft_suggestion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['draft', 'source_system'], name='fundamental_draft_i_49e764_idx'), models.Index(fields=['source_system', 'source_ref'], name='fundamental_source__899adb_idx'), models.Index(fields=['draft', 'accepted'], name='fundamental_draft_i_0733a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewQueueEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('discard', 'Discarded'), ('approve', 'Approved for Consideration'), ('promote', 'Promoted (draft canonical)'), ('promote_and_publish', 'Promoted + Published'), ('archive', 'Archived')], db_index=True, help_text='The formal action taken', max_length=30)),
                ('decided_at', models.DateTimeField(auto_now_add=True, help_text='When the decision was recorded')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional rationale or context for this decision')),
                ('decided_by', models.ForeignKey(blank=True, help_text='User who made this decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_decisions', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(help_text='The MillDraft this decision was made on', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='fundamentals.milldraft')),
            ],
            options={
                'verbose_name': 'Review Queue Entry',
                'verbose_name_plural': 'Review Queue Entries',
                'db_table': 'fundamentals_review_queue_entry',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['draft', '-decided_at'], name='fundamental_draft_i_7fd8f9_idx'), models.Index(fields=['decided_by', '-decided_at'], name='fundamental_decided_40b0a0_idx'), models.Index(fields=['decision', '-decided_at'], name='fundamental_decisio_fe99bb_idx')],
            },
        ),
    ]
