# Generated by Django 5.2.8 on 2026-09-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundamentals', '0003_reviewqueueentry_milldraftsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milldraftsuggestion',
            name='source_system',
            field=models.CharField(choices=[('stackroom', 'Stackroom'), ('concord', 'Concord'), ('gristmill', 'Grist Mill'), ('copydesk', 'Copy Desk'), ('in_editor', 'In-Editor (Inkwell / Clio)'), ('manual', 'Manual')], db_index=True, help_text='Which source system produced this suggestion', max_length=20),
        ),
    ]
