# Generated by Django 5.2.8 on 2026-06-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_phase_b_device_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationretentionpolicy',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='conversationauditevent',
            new_name='chat_conver_convers_64b42a_idx',
            old_name='chat_convaud_conv_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationauditevent',
            new_name='chat_conver_actor_i_3b4844_idx',
            old_name='chat_convaud_actor_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='participantverification',
            new_name='chat_partic_convers_a815d3_idx',
            old_name='chat_pv_conv_verifier_idx',
        ),
        migrations.RenameIndex(
            model_name='participantverification',
            new_name='chat_partic_convers_d00aa2_idx',
            old_name='chat_pv_conv_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevicesession',
            new_name='chat_userde_user_id_3d54c0_idx',
            old_name='chat_userdev_user_id_isactive_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevicesession',
            new_name='chat_userde_user_id_b9e19d_idx',
            old_name='chat_userdev_user_id_lastseen_idx',
        ),
        migrations.AlterField(
            model_name='conversationauditevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='conversationauditevent',
            name='event_type',
            field=models.CharField(choices=[('conversation_created', 'Conversation Created'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('message_sent', 'Message Sent'), ('device_verified', 'Device Verified'), ('device_revoked', 'Device Revoked')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='conversationretentionpolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participantverification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userdevicesession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
