# Generated by Django 5.2.8 on 2026-06-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_conversationkeybundle_ephemeral_public_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationkeybundle',
            new_name='chat_conver_convers_ae2893_idx',
            old_name='chat_ckb_conv_device_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='audio_iv',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
