# Generated by Django 5.2.8 on 2026-06-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_lwc3_chatmessage_audio_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_key_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
