# Generated by Django 5.2.8 on 2026-01-03 19:58

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('list', 'List'), ('project', 'Project')], default='list', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectColumn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField()),
                ('semantic_type', models.CharField(blank=True, choices=[('backlog', 'Backlog'), ('ready', 'Ready'), ('doing', 'Doing'), ('blocked', 'Blocked'), ('done', 'Done')], max_length=20, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.project')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projectcolumn')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='projects_pr_sponsor_18a45d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='projects_pr_sponsor_c8f9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['author', '-created_at'], name='projects_pr_author__dec38e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['submitted_by', '-created_at'], name='projects_pr_submitt_98c485_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['mode', '-updated_at'], name='projects_pr_mode_9170ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='projects_project_slug_sponsor_unique'),
        ),
        migrations.AddIndex(
            model_name='projectcolumn',
            index=models.Index(fields=['project', 'position'], name='projects_pr_project_5c25b1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcolumn',
            index=models.Index(fields=['project', 'semantic_type'], name='projects_pr_project_6d6b11_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcolumn',
            constraint=models.UniqueConstraint(fields=('project', 'position'), name='projects_projectcolumn_project_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectcolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('semantic_type__isnull', False)), fields=('project', 'semantic_type'), name='projects_projectcolumn_project_semantic_unique'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'column', 'position'], name='projects_ta_project_897728_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('column', 'position'), name='projects_task_column_position_unique'),
        ),
    ]
