# Generated by Django 5.2.8 on 2026-07-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_kanban_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcolumn',
            name='semantic_type',
            field=models.CharField(blank=True, choices=[('backlog', 'Backlog'), ('ready', 'Ready'), ('doing', 'Doing'), ('started', 'Started'), ('needs_review', 'Needs Review'), ('blocked', 'Blocked'), ('done', 'Done')], max_length=20, null=True),
        ),
    ]
