# Generated by Django 5.2.8 on 2026-01-03 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=99, unique=True)),
                ('display_name', models.CharField(help_text='Your public facing screen name.', max_length=48)),
                ('quick_intro', models.TextField(blank=True, default='', help_text='A quick bit about yourself.', max_length=300)),
                ('avatar_url', models.CharField(blank=True, default='', help_text='Avatar image URL', max_length=512)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
