# Generated by Codex on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Profile image storage key",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="background_image",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Background image storage key",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio_markdown",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
    ]
