# Generated by Django 5.2.8 on 2026-03-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_profile_images_and_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='right_now',
            field=models.TextField(blank=True, default='', help_text='A few words how you are right now (totally optional).', max_length=200),
        ),
    ]
