# Generated by Django 5.2.8 on 2026-04-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_practice_area_location'),
        ('profiles', '0004_userprofile_right_now'),
    ]

    operations = [
    ]
