# Generated by Django 5.2.8 on 2026-05-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_skills_work_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User UI preferences (e.g. dashboard settings).'),
        ),
    ]
