# Generated by Django 5.2.8 on 2026-05-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_revamp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='badge',
            name='unique_badge_per_profile',
        ),
        migrations.RemoveConstraint(
            model_name='featuredlink',
            name='unique_featuredlink_position',
        ),
        migrations.RemoveConstraint(
            model_name='pinnedtrack',
            name='unique_pinnedtrack_position',
        ),
        migrations.RemoveConstraint(
            model_name='qaitem',
            name='unique_qaitem_position',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quick_link',
            field=models.URLField(blank=True, default='', help_text='Personal or work link (website, IG, etc.)', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='who_are_you',
            field=models.CharField(blank=True, default='', help_text="How you'd describe yourself to the group.", max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='why_are_you_here',
            field=models.CharField(blank=True, default='', help_text="Why you joined / what you're looking for.", max_length=512),
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='featuredlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nowplaying',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pinnedshowcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pinnedtrack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profiletheme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qaitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('profile', 'glyph')},
        ),
        migrations.AlterUniqueTogether(
            name='featuredlink',
            unique_together={('profile', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='pinnedtrack',
            unique_together={('showcase', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='qaitem',
            unique_together={('profile', 'position')},
        ),
    ]
