# Generated by Django 5.2.8 on 2026-06-09 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_group_dispatch_policy'),
        ('profiles', '0010_userprofile_intro_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfileFieldDef',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('url', 'URL'), ('tags', 'Tags'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('default_visibility', models.CharField(choices=[('group_only', 'Group only'), ('public', 'Public')], default='group_only', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_shareable', models.BooleanField(default=False)),
                ('owner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_field_defs', to='groups.group')),
                ('source_field_def', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='profiles.groupprofilefielddef')),
            ],
            options={
                'ordering': ['owner_group', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MemberGroupProfileValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('group_only', 'Group only'), ('public', 'Public')], default='group_only', max_length=16)),
                ('field_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_values', to='profiles.groupprofilefielddef')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile_values', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_profile_values', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['field_def__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('member', 'field_def', 'group'), name='profiles_member_fielddef_group_unique')],
            },
        ),
    ]
