# Generated by Django 5.2.8 on 2026-01-23 04:19

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BazaarOffering',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('shape', models.CharField(choices=[('service', 'Service'), ('event', 'Event'), ('program', 'Program'), ('product', 'Product')], help_text='Fulfillment semantics: service, event, program, or product.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('unavailable', 'Unavailable'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members only'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('asset_object_id', models.UUIDField(blank=True, help_text='UUID of the referenced asset.', null=True)),
                ('price_amount', models.PositiveIntegerField(default=0, help_text='List price in minor units (smallest currency unit, e.g., cents).')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3)),
                ('is_free', models.BooleanField(default=False, help_text='If True, buyer pays 0 (effective price) without changing list price.')),
                ('price_config', models.JSONField(blank=True, default=dict, help_text='Future: promo windows, discounts, sliding scale, pay-what-you-can.')),
                ('fulfillment_type', models.CharField(choices=[('manual', 'Manual'), ('event', 'Event'), ('digital', 'Digital'), ('program', 'Program')], default='manual', max_length=20)),
                ('fulfillment_config', models.JSONField(blank=True, default=dict, help_text='Shape-specific fulfillment settings (v1+).')),
                ('asset_content_type', models.ForeignKey(blank=True, help_text='Content type of the referenced asset (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_offering_assets', to='contenttypes.contenttype')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bazaar Offering',
                'verbose_name_plural': 'Bazaar Offerings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BazaarOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='Amount in minor units (smallest currency unit, e.g., cents).')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('fulfilling', 'Fulfilling'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('buyer_note', models.TextField(blank=True, default='', help_text='Optional note from buyer to vendor.')),
                ('vendor_note', models.TextField(blank=True, default='', help_text='Internal note from vendor (not visible to buyer).')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', help_text='Stripe PaymentIntent ID.', max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, default='', help_text='Stripe Charge ID.', max_length=255)),
                ('offering_snapshot', models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of offering terms at confirm-time.')),
                ('buyer', models.ForeignKey(help_text='The user making the purchase.', on_delete=django.db.models.deletion.PROTECT, related_name='bazaar_orders', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(help_text='The offering being purchased.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='bazaar.bazaaroffering')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BazaarFulfillmentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('vendor', 'Vendor'), ('system', 'System')], default='system', help_text='Whether action was by vendor or system.', max_length=20)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('delivered', 'Delivered'), ('auto_delivered', 'Auto delivered')], help_text='Type of fulfillment event.', max_length=30)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this fulfillment action.')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who performed the action (if vendor action).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_fulfillment_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='The order this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_events', to='bazaar.bazaarorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('service', 'Service'), ('bundle', 'Bundle')], default='physical', max_length=20)),
                ('primary_file_id', models.UUIDField(blank=True, help_text='Reference to primary file/media asset (UUID).', null=True)),
                ('requires_shipping', models.BooleanField(default=False, help_text='Whether this product requires physical shipping.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', help_text='Asset lifecycle; does not imply it is currently offered.', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bazaar Product',
                'verbose_name_plural': 'Bazaar Products',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='bazaaroffering',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='bazaar_baza_sponsor_acc0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaaroffering',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='bazaar_baza_sponsor_fd12a5_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaaroffering',
            index=models.Index(fields=['author', '-created_at'], name='bazaar_baza_author__3caf76_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaaroffering',
            index=models.Index(fields=['submitted_by', '-created_at'], name='bazaar_baza_submitt_fa4c46_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaaroffering',
            index=models.Index(fields=['status', 'shape'], name='bazaar_baza_status_527dad_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaaroffering',
            index=models.Index(fields=['asset_content_type', 'asset_object_id'], name='bazaar_baza_asset_c_7d7001_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaaroffering',
            index=models.Index(fields=['visibility', 'status'], name='bazaar_baza_visibil_26c4b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='bazaaroffering',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='bazaar_bazaaroffering_slug_sponsor_unique'),
        ),
        migrations.AddIndex(
            model_name='bazaarorder',
            index=models.Index(fields=['buyer', '-created_at'], name='bazaar_baza_buyer_i_c563d7_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaarorder',
            index=models.Index(fields=['status', '-created_at'], name='bazaar_baza_status_0512fe_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaarorder',
            index=models.Index(fields=['offering', '-created_at'], name='bazaar_baza_offerin_0205b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaarfulfillmentevent',
            index=models.Index(fields=['order', '-created_at'], name='bazaar_baza_order_i_93a446_idx'),
        ),
        migrations.AddIndex(
            model_name='bazaarfulfillmentevent',
            index=models.Index(fields=['event_type', '-created_at'], name='bazaar_baza_event_t_50a3af_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='bazaar_prod_sponsor_3ee0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='bazaar_prod_sponsor_7fcc58_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['author', '-created_at'], name='bazaar_prod_author__42118d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['submitted_by', '-created_at'], name='bazaar_prod_submitt_1fc3d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='bazaar_product_slug_sponsor_unique'),
        ),
    ]
