# Generated by Django 5.2.8 on 2026-03-25 22:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0009_admission_policy_to_group'),
        ('writing', '0011_leaf_leafcomment_leaf_writing_lea_author__836cc6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sources_config', models.JSONField(default=list, help_text='Per-channel configs: [{source_id, config}]')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, defer execution until this time', null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_events_created', to=settings.AUTH_USER_MODEL)),
                ('writing_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_events', to='writing.writingpiece')),
            ],
            options={
                'verbose_name': 'Publish Event',
                'verbose_name_plural': 'Publish Events',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('activity_stream', 'Activity Stream'), ('linkedin', 'LinkedIn'), ('email', 'Email / Newsletter'), ('rss', 'RSS'), ('webhook', 'Webhook')], db_index=True, max_length=32)),
                ('label', models.CharField(help_text="Display name, e.g. 'Group Activity Stream'", max_length=128)),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for per-publish channel config fields')),
                ('tier_required', models.CharField(choices=[('free', 'Free'), ('community', 'Community'), ('persona', 'Persona')], default='free', help_text='Minimum tier required to use this channel', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_sources', to='groups.group')),
            ],
            options={
                'verbose_name': 'Distribution Source',
                'verbose_name_plural': 'Distribution Sources',
                'ordering': ['kind', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=512)),
                ('synopsis', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('channel_config', models.JSONField(blank=True, default=dict)),
                ('channel_response', models.JSONField(blank=True, default=dict)),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='success', max_length=16)),
                ('failure_reason', models.CharField(blank=True, max_length=512)),
                ('publish_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to='distribution.publishevent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_records', to='distribution.source')),
            ],
            options={
                'verbose_name': 'Share Record',
                'verbose_name_plural': 'Share Records',
                'ordering': ['-shared_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='publishevent',
            index=models.Index(fields=['writing_piece', 'status'], name='distributio_writing_89df0c_idx'),
        ),
        migrations.AddIndex(
            model_name='publishevent',
            index=models.Index(fields=['status', 'scheduled_at'], name='distributio_status_3982d4_idx'),
        ),
        migrations.AddIndex(
            model_name='sharerecord',
            index=models.Index(fields=['publish_event', 'source'], name='distributio_publish_f29411_idx'),
        ),
        migrations.AddIndex(
            model_name='sharerecord',
            index=models.Index(fields=['source', 'shared_at'], name='distributio_source__1394d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharerecord',
            constraint=models.UniqueConstraint(fields=('publish_event', 'source'), name='unique_share_per_event_source'),
        ),
    ]
