# Generated by Django 5.2.8 on 2025-12-22 22:27

import django.db.models.deletion
import django.utils.timezone
import fundamentals.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('default_channel', models.CharField(choices=[('messages', 'messages'), ('activity', 'activity'), ('system', 'system')], default='activity', max_length=24)),
                ('default_priority', models.CharField(choices=[('critical', 'critical'), ('normal', 'normal'), ('low', 'low')], default='normal', max_length=16)),
                ('suppressible_by_user', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('aggregate_count', models.PositiveIntegerField(default=1)),
                ('last_occurred_at', models.DateTimeField()),
                ('toast_shown_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_up_at', models.DateTimeField(blank=True, null=True)),
                ('bucket', models.CharField(choices=[('messages', 'messages'), ('activity', 'activity'), ('system', 'system')], default='activity', max_length=24)),
                ('priority', models.CharField(choices=[('critical', 'critical'), ('normal', 'normal'), ('low', 'low')], default='normal', max_length=16)),
                ('dedupe_key', models.CharField(db_index=True, max_length=128)),
                ('aggregate_key', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('bucket', models.CharField(blank=True, max_length=24, null=True)),
                ('activity_code', models.CharField(blank=True, max_length=64, null=True)),
                ('level', models.CharField(choices=[('mute', 'mute'), ('digest', 'digest'), ('realtime', 'realtime')], default='realtime', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('digest_frequency', models.CharField(choices=[('off', 'off'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly')], default='daily', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_label', models.CharField(choices=[('user', 'user'), ('group', 'group'), ('system', 'system')], default='user', max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('context_id', models.CharField(blank=True, max_length=64, null=True)),
                ('verb', models.CharField(max_length=64)),
                ('activity_code', models.CharField(blank=True, max_length=64)),
                ('channel', models.CharField(choices=[('messages', 'messages'), ('activity', 'activity'), ('system', 'system')], default='activity', max_length=24)),
                ('priority', models.CharField(choices=[('critical', 'critical'), ('normal', 'normal'), ('low', 'low')], default='normal', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(db_index=True, max_length=128)),
                ('aggregate_key', models.CharField(db_index=True, max_length=128)),
                ('audience', models.JSONField(default=dict)),
                ('occurs_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('context_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ActionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('context_id', models.CharField(max_length=64)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='activity.action')),
                ('context_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ActionOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='activity.action')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
