# Generated by Django 5.2.8 on 2025-12-22 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='activity.activitytype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activity.action'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='actioncontext',
            index=models.Index(fields=['action'], name='activity_ac_action__fe142b_idx'),
        ),
        migrations.AddIndex(
            model_name='actioncontext',
            index=models.Index(fields=['context_content_type', 'context_id'], name='activity_ac_context_5e77c5_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['dedupe_key'], name='activity_ac_dedupe__bdb068_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['aggregate_key'], name='activity_ac_aggrega_3d3e52_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['occurs_at'], name='activity_ac_occurs__0bdfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['activity_code'], name='activity_ac_activit_720a43_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['channel'], name='activity_ac_channel_fbb91b_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['priority'], name='activity_ac_priorit_0ddb72_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='activity_no_recipie_523283_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'bucket', 'is_read'], name='activity_no_recipie_2d1c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'aggregate_key'], name='activity_no_recipie_771b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'priority', 'is_read'], name='activity_no_recipie_d17c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['last_occurred_at'], name='activity_no_last_oc_429c43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'dedupe_key')},
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'bucket'], name='activity_no_user_id_4501d6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'activity_code'], name='activity_no_user_id_7b85ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'bucket', 'activity_code')},
        ),
    ]
