# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[("mute", "mute"), ("digest", "digest"), ("realtime", "realtime")],
                default="realtime",
                max_length=16,
            ),
        ),
    ]
