# Generated by Django 5.2.8 on 2026-03-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_notification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
