# Generated by Django 5.2.8 on 2026-04-21 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('writing', '0025_rename_writing_wri_analysi_bbd3b1_idx_writing_wri_analysi_35ea8a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_type', models.CharField(choices=[('selection', 'Selection'), ('document', 'Document')], default='selection', max_length=20)),
                ('selected_text', models.TextField(blank=True, null=True)),
                ('anchor_start_offset', models.IntegerField(default=0)),
                ('anchor_end_offset', models.IntegerField(default=0)),
                ('note_text', models.TextField(blank=True, default='')),
                ('is_flagged', models.BooleanField(default=False)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darts', to='writing.writingpiece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'artifact'], name='reading_dar_user_id_ea5f3b_idx'), models.Index(fields=['artifact'], name='reading_dar_artifac_b471e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('times_read', models.IntegerField(default=0)),
                ('flagged_to_reread', models.BooleanField(default=False)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_stats', to='writing.writingpiece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'artifact'], name='reading_rea_user_id_6b7323_idx')],
                'unique_together': {('user', 'artifact')},
            },
        ),
    ]
