# Generated by Django 5.2.8 on 2026-02-04 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wrong_word', models.CharField(db_index=True, help_text='The misspelled word (lowercase)', max_length=100, unique=True)),
                ('correct_word', models.CharField(help_text='The correct spelling', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this correction has been applied')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this correction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell_corrections_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spell Correction',
                'verbose_name_plural': 'Spell Corrections',
                'ordering': ['wrong_word'],
            },
        ),
        migrations.CreateModel(
            name='SpellSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wrong_word', models.CharField(db_index=True, help_text='The misspelled word', max_length=100)),
                ('correct_word', models.CharField(help_text='Suggested correct spelling', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Optional note from reviewer (e.g., reason for rejection)')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Superadmin who reviewed this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell_suggestions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(help_text='User who submitted this suggestion', on_delete=django.db.models.deletion.CASCADE, related_name='spell_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spell Suggestion',
                'verbose_name_plural': 'Spell Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
