# Generated by Django 5.2.1 on 2025-11-21 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('threadworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionview',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='threadworks.discussion'),
        ),
        migrations.AddField(
            model_name='discussionview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='sponsor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='forum',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='threadworks.forum'),
        ),
        migrations.AddField(
            model_name='forummembership',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='threadworks.forum'),
        ),
        migrations.AddField(
            model_name='forummembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threadworks.discussion'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threadworks.forum'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='threadworks.discussion'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='threadworks.post'),
        ),
        migrations.AddField(
            model_name='forumnotification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threadworks.post'),
        ),
        migrations.AddField(
            model_name='discussionview',
            name='last_post_seen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_markers', to='threadworks.post'),
        ),
        migrations.AddField(
            model_name='postflag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='threadworks.post'),
        ),
        migrations.AddField(
            model_name='postflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postflag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='threadworks.post'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['visibility', '-updated_at'], name='threadworks_visibil_dfcdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', '-updated_at'], name='threadworks_sponsor_96a5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['forum', '-created_at'], name='threadworks_forum_i_b42ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['created_by', '-created_at'], name='threadworks_created_4cdc07_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['status', '-created_at'], name='threadworks_status_011cd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussion',
            unique_together={('forum', 'slug')},
        ),
        migrations.AddIndex(
            model_name='forummembership',
            index=models.Index(fields=['forum', 'role'], name='threadworks_forum_i_697aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='forummembership',
            index=models.Index(fields=['user', '-created_at'], name='threadworks_user_id_8d6f65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forummembership',
            unique_together={('forum', 'user')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['discussion', 'created_at'], name='threadworks_discuss_a58b99_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='threadworks_author__deaffc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent', 'created_at'], name='threadworks_parent__cac35d_idx'),
        ),
        migrations.AddIndex(
            model_name='forumnotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='threadworks_user_id_daeae2_idx'),
        ),
        migrations.AddIndex(
            model_name='forumnotification',
            index=models.Index(fields=['forum', '-created_at'], name='threadworks_forum_i_7b5c21_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionview',
            index=models.Index(fields=['user', '-updated_at'], name='threadworks_user_id_c40c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionview',
            index=models.Index(fields=['discussion', '-updated_at'], name='threadworks_discuss_ebbf39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionview',
            unique_together={('discussion', 'user')},
        ),
        migrations.AddIndex(
            model_name='postflag',
            index=models.Index(fields=['is_resolved', '-created_at'], name='threadworks_is_reso_212728_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postflag',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['post', 'reaction'], name='threadworks_post_id_d26b55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('post', 'user', 'reaction')},
        ),
    ]
