# Generated by Django 5.2.8 on 2026-05-14 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadworks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='audience_members',
            field=models.ManyToManyField(blank=True, help_text="Explicit member list used when audience_type='subset'.", related_name='subset_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='audience_type',
            field=models.CharField(choices=[('all_members', 'All Group Members'), ('subset', 'Specific Members')], default='all_members', max_length=20),
        ),
        migrations.AddField(
            model_name='forum',
            name='auto_add_new_members',
            field=models.BooleanField(default=True, help_text='When audience is All Group Members, automatically include new group members.'),
        ),
    ]
