# Generated by Django 5.2.8 on 2026-07-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadworks', '0006_discussion_updated_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryvalueevent',
            name='event_type',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('reply', 'Reply'), ('quoted_reply', 'Quoted Reply'), ('author_distinguished_reply', 'Author-Distinguished Reply'), ('creation_signal', 'Creation-Time Signal'), ('moderator_adjustment', 'Moderator Adjustment'), ('summary_approved', 'Summary Approved'), ('decay', 'Scheduled Decay')], max_length=30),
        ),
    ]
