# Generated by Django 5.2.8 on 2026-01-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('hidden_theme_ids', models.JSONField(blank=True, default=list)),
                ('group_themes', models.JSONField(blank=True, default=list)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to='groups.group')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
