# Generated by Django 5.2.8 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('steward', 'Steward'), ('member', 'Member'), ('helper', 'Helper')], max_length=50, unique=True),
        ),
    ]
