# Generated by Django 5.2.8 on 2026-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stackroom_library_id',
            field=models.UUIDField(blank=True, help_text="UUID of this user's personal Stackroom library. Set when the library is first created.", null=True),
        ),
    ]
