# Generated by Django 5.2.8 on 2026-01-03 19:17

import fundamentals.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('event_format', models.CharField(choices=[('workshop', 'Workshop'), ('lecture', 'Lecture'), ('discussion', 'Discussion'), ('field_trip', 'Field Trip'), ('social', 'Social'), ('ceremony', 'Ceremony'), ('practice', 'Practice'), ('work_party', 'Work Party')], default='workshop', max_length=50)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline_hours', models.PositiveIntegerField(default=24)),
                ('visible_to_parent', models.BooleanField(default=False, help_text="Make this event visible on parent group's calendar (circles only)")),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Decorator-specific data: instructions, learning outcomes, etc.')),
            ],
            options={
                'verbose_name': 'Event Decorator Assignment',
                'verbose_name_plural': 'Event Decorator Assignments',
            },
        ),
        migrations.CreateModel(
            name='EventFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('follow_type', models.CharField(choices=[('following', 'Following'), ('interested', 'Interested'), ('organizer', 'Organizer')], default='following', max_length=12)),
                ('notify_new_occurrences', models.BooleanField(default=True)),
                ('notify_changes', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Follower',
            },
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('recurrence_id', models.DateTimeField(help_text='Canonical instance key')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('cancellation_reason', models.TextField(blank=True, default=None, null=True)),
                ('title_override', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('location_override', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actual_attendance', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Occurrence',
                'verbose_name_plural': 'Event Occurrences',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('rrule', models.TextField(blank=True, help_text='RFC 5545 RRULE string for pattern-based recurrence')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Series',
                'verbose_name_plural': 'Event Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatheringExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('accommodation_available', models.BooleanField(default=False)),
                ('meals_included', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gathering Extension',
                'verbose_name_plural': 'Gathering Extensions',
            },
        ),
        migrations.CreateModel(
            name='OccurrenceAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going'), ('attended', 'Attended'), ('no_show', 'No Show')], default='going', max_length=12)),
                ('registration_notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='1-5 stars', null=True)),
            ],
            options={
                'verbose_name': 'Occurrence Attendee',
                'verbose_name_plural': 'Occurrence Attendees',
            },
        ),
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(help_text='Machine name: is_potluck, is_open_to_public', unique=True)),
                ('name', models.CharField(help_text='Display name: Potluck, Open to Public', max_length=100)),
                ('icon', models.CharField(help_text='Emoji icon: 🍽️, 🌐', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('has_context_data', models.BooleanField(default=False, help_text='Does this decorator store additional context (instructions, etc.)?')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Decorator',
                'verbose_name_plural': 'Decorators',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='almanac_dec_slug_d555a7_idx'), models.Index(fields=['is_active'], name='almanac_dec_is_acti_7feff7_idx')],
            },
        ),
    ]
