# Generated by Django 5.2.8 on 2025-12-23 00:23

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(help_text='Machine name: is_potluck, is_open_to_public', unique=True)),
                ('name', models.CharField(help_text='Display name: Potluck, Open to Public', max_length=100)),
                ('icon', models.CharField(help_text='Emoji icon: 🍽️, 🌐', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('has_context_data', models.BooleanField(default=False, help_text='Does this decorator store additional context (instructions, etc.)?')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Decorator',
                'verbose_name_plural': 'Decorators',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='almanac_dec_slug_d555a7_idx'), models.Index(fields=['is_active'], name='almanac_dec_is_acti_7feff7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('event_format', models.CharField(choices=[('workshop', 'Workshop'), ('lecture', 'Lecture'), ('discussion', 'Discussion'), ('field_trip', 'Field Trip'), ('social', 'Social'), ('ceremony', 'Ceremony'), ('practice', 'Practice'), ('work_party', 'Work Party')], default='workshop', max_length=50)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline_hours', models.PositiveIntegerField(default=24)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Decorator-specific data: instructions, learning outcomes, etc.')),
                ('decorator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='almanac.decorator')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorator_assignments', to='almanac.event')),
            ],
            options={
                'verbose_name': 'Event Decorator Assignment',
                'verbose_name_plural': 'Event Decorator Assignments',
            },
        ),
        migrations.CreateModel(
            name='EventFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('follow_type', models.CharField(choices=[('following', 'Following'), ('interested', 'Interested'), ('organizer', 'Organizer')], default='following', max_length=12)),
                ('notify_new_occurrences', models.BooleanField(default=True)),
                ('notify_changes', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='almanac.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Follower',
            },
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('rrule', models.TextField(blank=True, help_text='RFC 5545 RRULE string for pattern-based recurrence')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='almanac.event')),
            ],
            options={
                'verbose_name': 'Event Series',
                'verbose_name_plural': 'Event Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('recurrence_id', models.DateTimeField(help_text='Canonical instance key')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('title_override', models.CharField(blank=True, max_length=200)),
                ('location_override', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('actual_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='almanac.eventseries')),
            ],
            options={
                'verbose_name': 'Event Occurrence',
                'verbose_name_plural': 'Event Occurrences',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='GatheringExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('accommodation_available', models.BooleanField(default=False)),
                ('meals_included', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gathering_extension', to='almanac.event')),
            ],
            options={
                'verbose_name': 'Gathering Extension',
                'verbose_name_plural': 'Gathering Extensions',
            },
        ),
        migrations.CreateModel(
            name='OccurrenceAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going'), ('attended', 'Attended'), ('no_show', 'No Show')], default='going', max_length=12)),
                ('registration_notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='almanac.eventoccurrence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Occurrence Attendee',
                'verbose_name_plural': 'Occurrence Attendees',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'created_at'], name='almanac_eve_status_6fcadc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_format'], name='almanac_eve_event_f_5e6ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdecorator',
            index=models.Index(fields=['decorator', 'event'], name='almanac_eve_decorat_672453_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdecorator',
            index=models.Index(fields=['event'], name='almanac_eve_event_i_af4610_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdecorator',
            unique_together={('event', 'decorator')},
        ),
        migrations.AddIndex(
            model_name='eventfollower',
            index=models.Index(fields=['event', 'user'], name='almanac_eve_event_i_48fd32_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfollower',
            index=models.Index(fields=['user', 'follow_type'], name='almanac_eve_user_id_495856_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventfollower',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventseries',
            index=models.Index(fields=['is_active', 'created_at'], name='almanac_eve_is_acti_c9f52c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventseries',
            index=models.Index(fields=['event'], name='almanac_eve_event_i_231d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['series', 'start'], name='almanac_eve_series__54707a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['start', 'end'], name='almanac_eve_start_54d432_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['is_cancelled', 'start'], name='almanac_eve_is_canc_b58933_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('start__lt', models.F('end'))), name='occ_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoccurrence',
            unique_together={('series', 'recurrence_id')},
        ),
        migrations.AddIndex(
            model_name='occurrenceattendee',
            index=models.Index(fields=['occurrence', 'status'], name='almanac_occ_occurre_8abdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrenceattendee',
            index=models.Index(fields=['user', 'status'], name='almanac_occ_user_id_742dca_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrenceattendee',
            index=models.Index(fields=['occurrence', 'user'], name='almanac_occ_occurre_8d4be9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrenceattendee',
            unique_together={('occurrence', 'user')},
        ),
    ]
