# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almanac', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdecorator',
            name='decorator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='almanac.decorator'),
        ),
        migrations.AddField(
            model_name='eventdecorator',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorator_assignments', to='almanac.event'),
        ),
        migrations.AddField(
            model_name='eventfollower',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='almanac.event'),
        ),
        migrations.AddField(
            model_name='eventfollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='almanac.event'),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='almanac.eventseries'),
        ),
        migrations.AddField(
            model_name='gatheringextension',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gathering_extension', to='almanac.event'),
        ),
        migrations.AddField(
            model_name='occurrenceattendee',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='almanac.eventoccurrence'),
        ),
        migrations.AddField(
            model_name='occurrenceattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'created_at'], name='almanac_eve_status_6fcadc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_format'], name='almanac_eve_event_f_5e6ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdecorator',
            index=models.Index(fields=['decorator', 'event'], name='almanac_eve_decorat_672453_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdecorator',
            index=models.Index(fields=['event'], name='almanac_eve_event_i_af4610_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdecorator',
            unique_together={('event', 'decorator')},
        ),
        migrations.AddIndex(
            model_name='eventfollower',
            index=models.Index(fields=['event', 'user'], name='almanac_eve_event_i_48fd32_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfollower',
            index=models.Index(fields=['user', 'follow_type'], name='almanac_eve_user_id_495856_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventfollower',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventseries',
            index=models.Index(fields=['is_active', 'created_at'], name='almanac_eve_is_acti_c9f52c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventseries',
            index=models.Index(fields=['event'], name='almanac_eve_event_i_231d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['series', 'start'], name='almanac_eve_series__54707a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['start', 'end'], name='almanac_eve_start_54d432_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['is_cancelled', 'start'], name='almanac_eve_is_canc_b58933_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('start__lt', models.F('end'))), name='occ_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoccurrence',
            unique_together={('series', 'recurrence_id')},
        ),
        migrations.AddIndex(
            model_name='occurrenceattendee',
            index=models.Index(fields=['occurrence', 'status'], name='almanac_occ_occurre_8abdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrenceattendee',
            index=models.Index(fields=['user', 'status'], name='almanac_occ_user_id_742dca_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrenceattendee',
            index=models.Index(fields=['occurrence', 'user'], name='almanac_occ_occurre_8d4be9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrenceattendee',
            unique_together={('occurrence', 'user')},
        ),
    ]
