# Generated by Django 5.2.8 on 2025-12-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_to_parent',
            field=models.BooleanField(default=False, help_text="Make this event visible on parent group's calendar (circles only)"),
        ),
    ]
