# Generated by Django 5.2.8 on 2025-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0002_event_visible_to_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurrence',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
