# Generated by Django 5.2.8 on 2025-12-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0003_allow_null_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='eventoccurrence',
            name='location_override',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='eventoccurrence',
            name='title_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
