# Generated by Django 5.2.8 on 2026-05-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puddlejump', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='libraryitem',
            new_name='puddlejump__library_d7b6ba_idx',
            old_name='puddlejump_library_order_idx',
        ),
        migrations.RenameIndex(
            model_name='libraryitem',
            new_name='puddlejump__library_c0216f_idx',
            old_name='puddlejump_library_folder_idx',
        ),
    ]
