# Generated by Django 5.2.8 on 2026-05-21 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlejump', '0004_libraryitemversion_libraryitem_current_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('path', models.TextField()),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_events', to='puddlejump.library')),
                ('library_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_events', to='puddlejump.libraryitem')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_events', to='puddlejump.libraryitemversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
