# Generated by Django 5.2.8 on 2026-05-21 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puddlejump', '0005_manifestevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField()),
                ('manifest_json', models.JSONField()),
                ('file_count', models.IntegerField()),
                ('total_size_bytes', models.BigIntegerField()),
                ('delivered_to', models.CharField(max_length=20)),
                ('delivery_key', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='puddlejump.library')),
            ],
            options={
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(default='weekly', max_length=20)),
                ('endpoint_type', models.CharField(default='internal', max_length=20)),
                ('endpoint_url', models.TextField(blank=True)),
                ('endpoint_credentials', models.JSONField(blank=True, default=dict)),
                ('retain_count', models.IntegerField(default=4)),
                ('last_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.CharField(default='standard', max_length=20)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_config', to='puddlejump.library')),
            ],
            options={
                'verbose_name': 'Snapshot Config',
            },
        ),
    ]
