# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanternmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('listmonk_id', models.IntegerField(unique=True)),
                ('listmonk_uuid', models.CharField(max_length=36, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('listmonk_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_lists', to='groups.group')),
            ],
            options={
                'db_table': 'lantern_mail_lists',
                'unique_together': {('group', 'display_name')},
            },
        ),
    ]
