# Generated by Django 5.2.8 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternmail', '0002_welcomeemaildraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeemaildraft',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
