# Generated by Django 5.2.8 on 2026-09-03 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0033_add_generation_fields_to_public_config'),
        ('lanternmail', '0003_alter_welcomeemaildraft_deleted_at'),
        ('publishing', '0005_contentplacement_order_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanternmailPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('ready', 'Ready'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('audience_kind', models.CharField(choices=[('members', 'Members'), ('subscribers', 'Subscribers'), ('public_followers', 'Public Followers'), ('custom', 'Custom')], default='members', max_length=30)),
                ('listmonk_campaign_id', models.IntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ingest_status', models.CharField(choices=[('pending', 'Pending'), ('eligible', 'Eligible'), ('ingested', 'Ingested'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lanternmail_posts', to='publishing.contentplacement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lanternmail_posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanternmail_posts', to='groups.group')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='lanternmail.lanternmaillist')),
                ('publication_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lanternmail_posts', to='publishing.publicationgroup')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'lanternmail_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
