# Generated by Django 5.2.8 on 2026-09-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternmail', '0004_lanternmailpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanternmailpost',
            name='body',
        ),
        migrations.AddField(
            model_name='lanternmailpost',
            name='body_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lanternmailpost',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
