# Generated by Django 5.2.8 on 2026-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanternmail', '0005_rich_body_mixin_swap_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanternmailpost',
            name='source_object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
