# Generated by Django 5.2.8 on 2026-09-16 16:28

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clio', '0002_drop_legacy_beryl_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeeperRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keeper_id', models.SlugField(help_text="Kebab-case slug, e.g. 'recency-keeper' or 'count-nag-keeper.junk-pile'.", max_length=200)),
                ('keeper_name', models.CharField(max_length=200)),
                ('owner_subsystem', models.CharField(db_index=True, help_text='The Django app or service that spawned and owns this Keeper.', max_length=200)),
                ('watch_scope', models.TextField(help_text='Plain-English description of what the Keeper observes. Human-readable only; not machine-parsed.')),
                ('question_shapes', models.JSONField(blank=True, default=list, help_text='List of {intent, description, answer_task}. Empty for proactive-only Keepers.')),
                ('intents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Denormalized from question_shapes[].intent for indexed routing lookups (AD-11).', size=None)),
                ('finding_cadence', models.CharField(choices=[('reactive', 'Reactive'), ('proactive', 'Proactive'), ('both', 'Both')], max_length=16)),
                ('closing_mode', models.CharField(choices=[('drop', 'Drop'), ('archive', 'Archive')], default='archive', help_text='Declared preference at registration time (AD-10); may be confirmed or overridden at deregistration (AD-5).', max_length=16)),
                ('instance_params', models.JSONField(blank=True, default=dict, help_text='Keeper-specific configuration. Opaque to Clio; relayed to the Keeper unchanged.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'keeper_id'], name='clio_keeper_status_c73999_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('keeper_id',), name='unique_active_keeper_id')],
            },
        ),
    ]
