# Generated by Django 5.2.8 on 2026-09-16 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clio', '0003_keeperregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeeperFinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keeper_id', models.CharField(db_index=True, max_length=200)),
                ('finding_type', models.CharField(help_text='Keeper-defined slug describing what was found.', max_length=200)),
                ('finding_body', models.JSONField(blank=True, default=dict, help_text='Keeper-specific payload. Opaque beyond logging/storage.')),
                ('suggested_clio_signal', models.CharField(choices=[('nag', 'Nag'), ('notice', 'Notice'), ('suggest', 'Suggest')], max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['keeper_id', 'submitted_at'], name='clio_keeper_keeper__6ffed8_idx')],
            },
        ),
    ]
