# Generated by Django 5.2.8 on 2026-09-16 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clio', '0004_keeperfinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeperfinding',
            name='keeper_id',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(message='keeper_id must be dot-separated segments of letters, numbers, underscores, or hyphens.', regex='^[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)*$')]),
        ),
        migrations.AlterField(
            model_name='keeperregistration',
            name='keeper_id',
            field=models.CharField(db_index=True, help_text="Kebab-case slug, e.g. 'recency-keeper' or 'count-nag-keeper.junk-pile'.", max_length=200, validators=[django.core.validators.RegexValidator(message='keeper_id must be dot-separated segments of letters, numbers, underscores, or hyphens.', regex='^[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)*$')]),
        ),
    ]
