# Generated by Django 5.2.8 on 2026-09-28 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clio', '0005_alter_keeperfinding_keeper_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeperfinding',
            name='sponsor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='keeperfinding',
            name='sponsor_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keeperfinding',
            name='finding_body',
            field=models.JSONField(blank=True, default=dict, help_text="Keeper-specific payload. Opaque beyond logging/storage, with one light convention: an optional 'message' key, a human-readable string used verbatim if this finding is surfaced through Clio."),
        ),
        migrations.AddIndex(
            model_name='keeperfinding',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'submitted_at'], name='clio_keeper_sponsor_33d551_idx'),
        ),
    ]
