# Generated by Django 5.2.8 on 2026-03-14 18:43

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonsItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('person', 'Person'), ('organization', 'Organization'), ('group', 'Group'), ('project', 'Project'), ('place', 'Place'), ('event', 'Event')], default='', max_length=20)),
                ('curation_status', models.CharField(choices=[('captured', 'Captured'), ('in_curation', 'In Curation'), ('ready', 'Ready for Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='captured', max_length=20)),
                ('why_recommended', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_links', models.JSONField(blank=True, default=list)),
                ('instagram', models.URLField(blank=True, default='', max_length=500)),
                ('youtube', models.URLField(blank=True, default='', max_length=500)),
                ('rss', models.URLField(blank=True, default='', max_length=500)),
                ('location_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, default='', help_text='Original submitted URL', max_length=500)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Raw extraction output from Inkwell')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Flexible metadata (hours, pricing, etc.)')),
                ('founder', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commons_approvals', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('curated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commons_curations', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commons_recommendations', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('relation_type', models.CharField(choices=[('founded_by', 'Founded By'), ('located_in', 'Located In'), ('collaborates_with', 'Collaborates With'), ('teaches_at', 'Teaches At'), ('inspired_by', 'Inspired By'), ('affiliated_with', 'Affiliated With'), ('program_of', 'Program Of')], max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filaments_out', to='commons.commonsitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filaments_in', to='commons.commonsitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commonsitem',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='commons_com_sponsor_c4d524_idx'),
        ),
        migrations.AddIndex(
            model_name='commonsitem',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='commons_com_sponsor_1d2fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='commonsitem',
            index=models.Index(fields=['author', '-created_at'], name='commons_com_author__3d9ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='commonsitem',
            index=models.Index(fields=['submitted_by', '-created_at'], name='commons_com_submitt_93d0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='commonsitem',
            index=models.Index(fields=['curation_status'], name='commons_com_curatio_8fccac_idx'),
        ),
        migrations.AddIndex(
            model_name='commonsitem',
            index=models.Index(fields=['item_type'], name='commons_com_item_ty_7c6bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='commonsitem',
            index=models.Index(fields=['curation_status', '-created_at'], name='commons_com_curatio_be0d40_idx'),
        ),
        migrations.AddConstraint(
            model_name='commonsitem',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='commons_commonsitem_slug_sponsor_unique'),
        ),
        migrations.AddConstraint(
            model_name='filament',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='commons_filament_unique_relation'),
        ),
    ]
