# Generated by Django 5.2.8 on 2026-06-25 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_remove_filament'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0001_initial'),
        ('tapestry', '0001_initial'),
        ('writing', '0027_leafentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_json', models.JSONField(default=dict, help_text='ProseMirror content for rich text + images')),
                ('caption', models.TextField(blank=True, default='', help_text="Author's original commentary (especially for reference Leafs)")),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link'), ('voice', 'Voice')], default='text', max_length=16)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_preview', models.JSONField(blank=True, default=dict, help_text='Cached link preview metadata (title, image, description)')),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('library_only', models.BooleanField(default=False)),
                ('feeling_state', models.CharField(blank=True, default='', max_length=30)),
                ('intent_primary', models.CharField(blank=True, default='', max_length=30)),
                ('intent_secondary', models.CharField(blank=True, default='', max_length=30)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_leaves', to='files.storedfile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_leaves', to='files.storedfile')),
                ('origin_seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_leaves', to='writing.seed')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='tapestry.place')),
                ('promoted_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_origin', to='writing.workingdocument')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeafEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice')], max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_json', models.JSONField(blank=True, null=True)),
                ('shared', models.BooleanField(default=True)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_entry_audio', to='files.storedfile')),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_entry_images', to='files.storedfile')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='commons.leaf')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='leaf',
            index=models.Index(fields=['author', '-published_at'], name='commons_lea_author__758dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='leaf',
            index=models.Index(fields=['author', 'kind'], name='commons_lea_author__c507b0_idx'),
        ),
    ]
