# Generated by Django 5.2.8 on 2026-07-02 22:58

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCapture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('screencast', 'Screencast'), ('bridge_gathering', 'Bridge Gathering'), ('livestream', 'Livestream'), ('external_upload', 'External Upload')], default='screencast', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('media_file', models.CharField(blank=True, max_length=512)),
                ('has_video', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('intent_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('source_ref_object_id', models.UUIDField(blank=True, null=True)),
                ('visibility_scope', models.CharField(choices=[('circle', 'Circle'), ('group', 'Group'), ('crossroads', 'Crossroads')], default='crossroads', max_length=32)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_captures', to=settings.AUTH_USER_MODEL)),
                ('source_ref_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_json', models.JSONField(default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('stackroom_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='media_capture.mediacapture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediacapture',
            name='transcript',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_capture', to='media_capture.transcript'),
        ),
    ]
