# Generated by Django 5.2.8 on 2026-06-22 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0011_nested_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtriumSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text='Optional member-given title; auto-populated from first query if blank.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('session_context', models.TextField(blank=True, default='', help_text='Standing context injected at the start of every session — role, project state, working principles. The CLAUDE.md equivalent. Member-authored and editable between sessions.')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Updated on every new AtriumSessionEntry.', null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrium_sessions', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Atrium Session',
                'verbose_name_plural': 'Atrium Sessions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtriumSessionEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=16)),
                ('content', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='atrium.atriumsession')),
            ],
            options={
                'verbose_name': 'Atrium Session Entry',
                'verbose_name_plural': 'Atrium Session Entries',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
