# Generated by Django 5.2.8 on 2026-08-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrium', '0003_atriumsession_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atriumsession',
            name='pty_pid',
            field=models.IntegerField(blank=True, help_text='PID of the live PTY process for this session. Null when no PTY is running.', null=True),
        ),
    ]
