# Generated by Django 5.2.8 on 2026-08-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrium', '0005_distillate'),
        ('initiatives', '0023_aperturelog_source_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='atriumsession',
            name='initiative',
            field=models.ForeignKey(blank=True, help_text="When set, this session is scoped to a specific Initiative's ApertureLog.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atrium_sessions', to='initiatives.initiative'),
        ),
    ]
