# Generated by Codex on 2026-09-03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atrium", "0006_atriumsession_initiative"),
    ]

    operations = [
        migrations.AddField(
            model_name="atriumsession",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("anthropic-api", "Anthropic API"),
                    ("anthropic-claude-code", "Claude Code"),
                    ("openai-codex", "OpenAI Codex"),
                ],
                default="anthropic-api",
                help_text="Preferred cloud-agent provider for this human-visible session.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CloudAgentSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("anthropic-api", "Anthropic API"), ("anthropic-claude-code", "Claude Code"), ("openai-codex", "OpenAI Codex")], db_index=True, max_length=64)),
                ("provider_session_id", models.CharField(blank=True, default="", max_length=255)),
                ("linux_user", models.CharField(blank=True, default="", max_length=64)),
                ("working_directory", models.CharField(blank=True, default="", max_length=512)),
                ("policy", models.CharField(default="read_only", max_length=32)),
                ("status", models.CharField(choices=[("starting", "Starting"), ("running", "Running"), ("ready", "Ready"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="starting", max_length=32)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("atrium_session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cloud_agent_sessions", to="atrium.atriumsession")),
            ],
            options={
                "verbose_name": "Cloud Agent Session",
                "verbose_name_plural": "Cloud Agent Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="cloudagentsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("atrium_session", "provider"),
                name="unique_active_cloud_agent_session_per_provider",
            ),
        ),
    ]
