# Generated by Django 5.2.8 on 2026-09-08 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrium', '0007_ai_provider_cloudagentsession'),
        ('initiatives', '0023_aperturelog_source_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='atriumsessionentry',
            name='document_title',
            field=models.CharField(blank=True, default='', help_text='Populated when entry_type=document. Extracted from the <document title> envelope.', max_length=255),
        ),
        migrations.AddField(
            model_name='atriumsessionentry',
            name='entry_type',
            field=models.CharField(choices=[('message', 'Message'), ('document', 'Document')], db_index=True, default='message', help_text='message = prose bubble; document = rendered AtriumDocCard.', max_length=16),
        ),
        migrations.CreateModel(
            name='InitiativeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('format', models.CharField(default='markdown', help_text='Body format. Default: markdown.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(blank=True, help_text='Initiative this document belongs to. Null for personal sessions with no linked initiative.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_documents', to='initiatives.initiative')),
                ('session', models.ForeignKey(blank=True, help_text='The Atrium session that generated this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='atrium.atriumsession')),
                ('session_entry', models.OneToOneField(blank=True, help_text='The AtriumSessionEntry (entry_type=document) this record backs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_document', to='atrium.atriumsessionentry')),
            ],
            options={
                'verbose_name': 'Initiative Document',
                'verbose_name_plural': 'Initiative Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
