# Generated by Django 5.2.8 on 2026-01-03 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MillDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('grist_text', models.TextField()),
                ('ast_json', models.JSONField()),
                ('block_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('promoted', 'Promoted'), ('rejected', 'Rejected')], default='staged', max_length=20)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_object_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
