# Generated by Django 5.2.8 on 2026-02-19 23:39

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('flow_mode', models.CharField(choices=[('sequenced', 'Sequenced'), ('curated', 'Curated'), ('loose', 'Loose')], db_index=True, default='loose', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=16)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of learning objective strings')),
                ('delivery_type', models.CharField(choices=[('online', 'Online'), ('self_paced', 'Self-Paced'), ('hybrid', 'Hybrid'), ('in_person', 'In Person')], default='self_paced', max_length=16)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_object_id', models.UUIDField()),
                ('position', models.PositiveIntegerField()),
                ('section_title', models.CharField(blank=True, default='', help_text='Optional section heading for visual grouping in course outline', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='earthlab.course')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('tiptap_json', models.JSONField(blank=True, help_text='Rich content in TipTap JSON format', null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=16)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='earthlab_co_sponsor_221892_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='earthlab_co_sponsor_71e2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['author', '-created_at'], name='earthlab_co_author__f2848e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['submitted_by', '-created_at'], name='earthlab_co_submitt_b6cd14_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', '-updated_at'], name='earthlab_co_status_6ee5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['delivery_type'], name='earthlab_co_deliver_1956b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='earthlab_course_slug_sponsor_unique'),
        ),
        migrations.AddIndex(
            model_name='courseitem',
            index=models.Index(fields=['course', 'position'], name='earthlab_co_course__7368af_idx'),
        ),
        migrations.AddIndex(
            model_name='courseitem',
            index=models.Index(fields=['content_type', 'content_object_id'], name='earthlab_co_content_8358cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='unique_course_item_position'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.UniqueConstraint(fields=('course', 'content_type', 'content_object_id'), name='unique_course_item_content'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='earthlab_le_sponsor_98bd97_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='earthlab_le_sponsor_1af28c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['author', '-created_at'], name='earthlab_le_author__948ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['submitted_by', '-created_at'], name='earthlab_le_submitt_4c3a50_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', '-updated_at'], name='earthlab_le_status_198076_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='earthlab_lesson_slug_sponsor_unique'),
        ),
    ]
