# Generated by Django 5.2.8 on 2026-02-20 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('earthlab', '0001_initial'),
        ('stackroom', '0014_library_flow_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text="Optional title for this run (e.g. 'Spring 2026 Cohort')", max_length=255)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=16)),
                ('enrollment_policy', models.CharField(choices=[('open', 'Open'), ('invite', 'Invite Only'), ('closed', 'Closed')], default='open', max_length=16)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_enrollment', models.PositiveIntegerField(blank=True, help_text='Max enrollments (null = unlimited)', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='earthlab.course')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('waitlisted', 'Waitlisted')], default='enrolled', max_length=16)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='earthlab.courserun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earthlab_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='earthlab.enrollment')),
                ('lesson_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='earthlab.enrollment')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earthlab_progress', to='stackroom.library')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='courserun',
            index=models.Index(fields=['course', 'status'], name='earthlab_co_course__bde346_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course_run', 'status'], name='earthlab_en_course__90c9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='earthlab_en_user_id_e28bd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course_run', 'user'), name='unique_enrollment_per_run'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'status'], name='earthlab_le_enrollm_8d2831_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson_content_type', 'lesson_object_id'], name='earthlab_le_lesson__958700_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson_content_type', 'lesson_object_id'), name='unique_lesson_progress_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['enrollment', 'status'], name='earthlab_mo_enrollm_8f4d9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'library'), name='unique_module_progress_per_enrollment'),
        ),
    ]
