# stackroom/services/metadata_extraction.py

"""
Metadata Extraction for Artifacts

Generates extractive summary and keywords from document text for Simple Search.
All extraction is non-editable and programmatically generated.

Design:
- interior_summary: 2-3 sentences (~300-500 chars) extracted from original text
- keywords: Top 12 terms/phrases extracted via TF-IDF or RAKE
- 100% extractive (preserves original words for high fidelity)
- No LLM required (fast, deterministic, no API costs)

Can be swapped to use Inkwell summarization if available.
"""

from __future__ import annotations
import re
import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from stackroom.models import Artifact

logger = logging.getLogger(__name__)


# ============================================================================
# EXTRACTIVE SUMMARY
# ============================================================================

def extract_summary_simple(text: str, target_length: int = 400) -> str:
    """
    Simple extractive summarization using sentence position heuristics.

    Strategy:
    1. Split into sentences
    2. Weight by position (first paragraph > last paragraph > middle)
    3. Select top sentences until reaching target length
    4. Return in original order

    Args:
        text: Full document text
        target_length: Target character count (~300-500 recommended)

    Returns:
        Extractive summary (2-3 sentences from original text)
    """
    if not text or len(text.strip()) < 50:
        return ""

    # Split into sentences (simple regex, can be improved with nltk.sent_tokenize)
    sentences = re.split(r'(?<=[.!?])\s+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 20]

    if not sentences:
        return ""

    # If very short document, return first sentence
    if len(sentences) <= 2:
        return ' '.join(sentences[:2])

    # Score sentences by position
    scored_sentences = []
    num_sentences = len(sentences)

    for i, sentence in enumerate(sentences):
        # Position score (0-1, higher is better)
        if i < 3:
            # First 3 sentences (likely introduction)
            position_score = 1.0 - (i * 0.1)
        elif i >= num_sentences - 2:
            # Last 2 sentences (likely conclusion)
            position_score = 0.7
        else:
            # Middle sentences
            position_score = 0.5

        # Length penalty (avoid very short/very long sentences)
        length = len(sentence)
        if 50 <= length <= 150:
            length_score = 1.0
        elif length < 50:
            length_score = 0.6
        else:
            length_score = 0.8

        total_score = position_score * length_score
        scored_sentences.append((i, sentence, total_score))

    # Sort by score (descending) and select top sentences
    scored_sentences.sort(key=lambda x: x[2], reverse=True)

    # Select sentences until reaching target length
    selected_indices = []
    current_length = 0

    for idx, sentence, score in scored_sentences:
        if current_length + len(sentence) <= target_length:
            selected_indices.append(idx)
            current_length += len(sentence)

        if len(selected_indices) >= 3:  # Max 3 sentences
            break

    # Return in original order
    selected_indices.sort()
    selected_sentences = [sentences[i] for i in selected_indices]

    return ' '.join(selected_sentences)


def extract_summary_inkwell(text: str) -> str:
    """
    Use Inkwell summarization service if available.

    TODO: Integrate with existing Inkwell summarization method.
    User will provide code reference.

    Args:
        text: Full document text

    Returns:
        Summary generated by Inkwell
    """
    # Placeholder - will be implemented once user provides Inkwell integration
    raise NotImplementedError("Inkwell integration not yet configured")


# ============================================================================
# KEYWORD EXTRACTION
# ============================================================================

def extract_keywords_tfidf(text: str, top_n: int = 12) -> list[str]:
    """
    Extract keywords using TF-IDF (Term Frequency-Inverse Document Frequency).

    Simple implementation without external dependencies.
    For production, consider using scikit-learn's TfidfVectorizer.

    Args:
        text: Full document text
        top_n: Number of keywords to extract

    Returns:
        List of top N keywords (lowercase, deduplicated)
    """
    if not text or len(text.strip()) < 50:
        return []

    # Simple tokenization (split on non-word chars)
    words = re.findall(r'\b[a-z]{3,}\b', text.lower())

    if not words:
        return []

    # Common stop words (minimal set)
    stop_words = {
        'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'can', 'her',
        'was', 'one', 'our', 'out', 'day', 'get', 'has', 'him', 'his', 'how',
        'its', 'may', 'new', 'now', 'old', 'see', 'two', 'way', 'who', 'boy',
        'did', 'she', 'too', 'use', 'from', 'that', 'this', 'with', 'have',
        'will', 'what', 'when', 'which', 'their', 'said', 'each', 'make',
        'like', 'time', 'very', 'just', 'know', 'take', 'into', 'year',
        'your', 'good', 'some', 'could', 'them', 'than', 'then', 'been',
        'other', 'were', 'come', 'made', 'many', 'more', 'over', 'such',
        'only', 'down', 'also', 'back', 'well', 'much', 'where', 'there',
    }

    # Filter stop words and count frequencies
    filtered_words = [w for w in words if w not in stop_words]

    if not filtered_words:
        return []

    # Count term frequencies
    term_freq = {}
    for word in filtered_words:
        term_freq[word] = term_freq.get(word, 0) + 1

    # Sort by frequency
    sorted_terms = sorted(term_freq.items(), key=lambda x: x[1], reverse=True)

    # Return top N unique terms
    keywords = [term for term, freq in sorted_terms[:top_n]]

    return keywords


# ============================================================================
# MAIN EXTRACTION FUNCTION
# ============================================================================

def extract_artifact_metadata(
    artifact: Artifact,
    summary_method: str = 'simple',
    keywords_method: str = 'tfidf',
    metadata_version: str = '1.0-simple',
) -> dict[str, str | list[str]]:
    """
    Extract interior_summary and keywords from Artifact text.

    This is the main entry point called by the Celery task.

    Args:
        artifact: Artifact instance with .text populated
        summary_method: 'simple' | 'inkwell'
        keywords_method: 'tfidf' | 'rake'
        metadata_version: Version string to track extraction logic

    Returns:
        Dict with 'interior_summary', 'keywords', 'metadata_version'

    Raises:
        ValueError: If artifact.text is empty or invalid
    """
    if not artifact.text or len(artifact.text.strip()) < 50:
        logger.warning(f"Artifact {artifact.id} has insufficient text for extraction")
        return {
            'interior_summary': '',
            'keywords': [],
            'metadata_version': metadata_version,
        }

    # Extract summary
    if summary_method == 'inkwell':
        try:
            interior_summary = extract_summary_inkwell(artifact.text)
        except NotImplementedError:
            logger.info("Inkwell not configured, falling back to simple extraction")
            interior_summary = extract_summary_simple(artifact.text)
    else:
        interior_summary = extract_summary_simple(artifact.text)

    # Extract keywords
    if keywords_method == 'tfidf':
        keywords = extract_keywords_tfidf(artifact.text)
    else:
        # Future: Add RAKE or other methods
        keywords = extract_keywords_tfidf(artifact.text)

    logger.info(
        f"Extracted metadata for Artifact {artifact.id}: "
        f"summary={len(interior_summary)} chars, keywords={len(keywords)} terms"
    )

    return {
        'interior_summary': interior_summary,
        'keywords': keywords,
        'metadata_version': metadata_version,
    }
