# Generated by Django 5.2.8 on 2026-06-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drop',
            new_name='drop_drop_content_e68832_idx',
            old_name='drop_drop_ct_oid_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='drop',
            new_name='drop_drop_weight_15465f_idx',
            old_name='drop_drop_weight_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='drop',
            new_name='drop_drop_expires_cc18ef_idx',
            old_name='drop_drop_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='drop',
            new_name='drop_drop_handle_75ea6a_idx',
            old_name='drop_drop_handle_idx',
        ),
    ]
