# Generated by Django 5.2.8 on 2026-04-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_migrate_artifact_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshipannotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='relations_r_source__6dda53_idx',
            old_name='relations_r_source__idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='relations_r_target__214f54_idx',
            old_name='relations_r_target__idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='relations_r_relatio_23dc64_idx',
            old_name='relations_r_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='relationship',
            new_name='relations_r_source__5bef4c_idx',
            old_name='relations_r_source_type_idx',
        ),
        migrations.AlterField(
            model_name='relationshipannotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
