# Generated by Django 5.2.8 on 2026-09-08 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0035_group_tagline'),
        ('initiatives', '0024_actionrun_source_grant'),
        ('sourcework', '0002_externalconnection_credential_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionalData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, help_text="Record type: 'recruiter_contact', 'opportunity_candidate', etc.", max_length=80)),
                ('source_type', models.CharField(db_index=True, help_text="Origin system class: 'gmail', 'dice', 'indeed', 'manual', etc.", max_length=80)),
                ('source_locator', models.CharField(blank=True, default='', help_text='Human-readable resource locator, e.g. a URL or label path.', max_length=500)),
                ('source_external_id', models.CharField(blank=True, db_index=True, default='', help_text="Provider's own identifier for the source item (message ID, job ID, etc.).", max_length=255)),
                ('captured_at', models.DateTimeField(blank=True, help_text='When this record was ingested into Mixtape.', null=True)),
                ('observed_at', models.DateTimeField(blank=True, db_index=True, help_text='When the source item was observed at the external source (post date, email sent date, etc.).', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Minimally-transformed source material as received. Preserve for provenance.')),
                ('normalized_payload', models.JSONField(blank=True, default=dict, help_text='Typed normalized representation per kind (RecruiterContact shape, OpportunityCandidate shape, etc.).')),
                ('state', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('interesting', 'Interesting'), ('rejected', 'Rejected'), ('stale', 'Stale'), ('actioned', 'Actioned'), ('promoted', 'Promoted'), ('superseded', 'Superseded')], db_index=True, default='new', max_length=24)),
                ('confidence', models.FloatField(blank=True, help_text='Agent confidence score in [0, 1] for the normalized interpretation.', null=True)),
                ('freshness', models.CharField(blank=True, db_index=True, default='', help_text="Computed freshness tier: 'fresh', 'current', 'aging', 'stale_ish', 'presumed_stale'.", max_length=32)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Structured provenance record. Should capture: source, observed_at, shape_version, normalizer_version, agent, human judgment history.')),
                ('promoted_object_id', models.UUIDField(blank=True, help_text='PK of the durable Mixtape record this was promoted to.', null=True)),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionalDataMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='active', max_length=24)),
                ('position', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='workingset',
            name='execution_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Runtime metadata for the search execution: agent, query params, counts, warnings.'),
        ),
        migrations.AddField(
            model_name='workingset',
            name='search_brief',
            field=models.JSONField(blank=True, default=dict, help_text='Structured search criteria that produced this working set.'),
        ),
        migrations.AddField(
            model_name='workingset',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Source identifier for this working set, e.g. 'dice', 'gmail_recruiter', 'indeed'.", max_length=80),
        ),
        migrations.AddIndex(
            model_name='workingset',
            index=models.Index(fields=['source', 'status'], name='sourcework__source_a726ff_idx'),
        ),
        migrations.AddField(
            model_name='provisionaldata',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_data_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provisionaldata',
            name='promoted_content_type',
            field=models.ForeignKey(blank=True, help_text='ContentType of the durable Mixtape record this was promoted to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_provisional_data', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='provisionaldata',
            name='source_evidence',
            field=models.ForeignKey(blank=True, help_text='SourceEvidence record that grounds this provisional finding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_data_records', to='sourcework.sourceevidence'),
        ),
        migrations.AddField(
            model_name='provisionaldatamembership',
            name='provisional_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_set_memberships', to='sourcework.provisionaldata'),
        ),
        migrations.AddField(
            model_name='provisionaldatamembership',
            name='working_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_data_memberships', to='sourcework.workingset'),
        ),
        migrations.AddIndex(
            model_name='provisionaldata',
            index=models.Index(fields=['kind', 'state'], name='sourcework__kind_433397_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionaldata',
            index=models.Index(fields=['owner_user', 'state'], name='sourcework__owner_u_d01e00_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionaldata',
            index=models.Index(fields=['source_type', 'source_external_id'], name='sourcework__source__ed6821_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionaldata',
            index=models.Index(fields=['freshness', 'state'], name='sourcework__freshne_ff556f_idx'),
        ),
        migrations.AddConstraint(
            model_name='provisionaldatamembership',
            constraint=models.UniqueConstraint(fields=('working_set', 'provisional_data'), name='sourcework_unique_provisional_data_per_working_set'),
        ),
    ]
