# Generated by Django 5.2.8 on 2026-09-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcework', '0004_retire_provisionalthing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='provisionaldata',
            new_name='sourcework__group_i_e70042_idx',
            old_name='sourcework_pd_group_kind_state_idx',
        ),
    ]
