# Generated by Django 5.2.8 on 2026-09-22 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0037_alter_group_in_crossroads_directory'),
        ('initiatives', '0025_alter_aperturelogentry_authored_by'),
        ('sourcework', '0007_externalconnection_add_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(default='Current opportunity profile', max_length=120)),
                ('resume_label', models.CharField(blank=True, default='', max_length=255)),
                ('resume_version', models.CharField(blank=True, default='', max_length=80)),
                ('query_lanes', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('workplace_types', models.JSONField(blank=True, default=list)),
                ('employment_types', models.JSONField(blank=True, default=list)),
                ('seniority', models.JSONField(blank=True, default=list)),
                ('strong_domains', models.JSONField(blank=True, default=list)),
                ('strong_technologies', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('freshness_hours', models.PositiveIntegerField(default=72)),
                ('preferences', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='externalconnection',
            name='unique_connected_account_per_group_provider',
        ),
        migrations.AddField(
            model_name='workingset',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcework_working_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externalconnection',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcework_connections', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcework_working_sets', to='groups.group'),
        ),
        migrations.AddIndex(
            model_name='externalconnection',
            index=models.Index(fields=['owner', 'provider', 'status'], name='sourcework__owner_i_144631_idx'),
        ),
        migrations.AddIndex(
            model_name='workingset',
            index=models.Index(fields=['owner_user', 'status'], name='sourcework__owner_u_6a3fd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False), models.Q(('provider_account_id', ''), _negated=True)), fields=('group', 'provider', 'provider_account_id'), name='unique_connected_account_per_group_provider'),
        ),
        migrations.AddConstraint(
            model_name='externalconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True), ('owner__isnull', False), models.Q(('provider_account_id', ''), _negated=True)), fields=('owner', 'provider', 'provider_account_id'), name='sourcework_unique_member_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='workingset',
            constraint=models.CheckConstraint(condition=models.Q(('group__isnull', False), ('owner_user__isnull', False), _connector='OR'), name='sourcework_working_set_has_sponsor'),
        ),
        migrations.AddField(
            model_name='opportunityprofile',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='opportunityprofile',
            index=models.Index(fields=['owner_user', 'is_current'], name='sourcework__owner_u_e9b033_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityprofile',
            constraint=models.UniqueConstraint(fields=('owner_user', 'version'), name='sourcework_unique_opportunity_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='opportunityprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('owner_user',), name='sourcework_one_current_opportunity_profile'),
        ),
    ]
