# Generated by Django 5.2.8 on 2026-09-22 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcework', '0008_opportunityprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityApplicationDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], db_index=True, default='draft', max_length=24)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('letter_body', models.TextField(blank=True, default='')),
                ('generation_context', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(blank=True, default='', max_length=40)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_drafts', to='sourcework.provisionaldata')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_application_drafts', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_drafts', to='sourcework.opportunityprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner_user', 'status'], name='sourcework__owner_u_3b8657_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_user', 'opportunity'), name='sourcework_one_application_draft_per_member_opportunity')],
            },
        ),
    ]
