# Generated by Django 5.2.8 on 2026-02-03 03:25

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, default='', help_text='Canonical text content of the list (plaintext micro-grammar)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'abstract': False,
                'indexes': [models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='lists_list_sponsor_3c6de7_idx'), models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='lists_list_sponsor_c57a9f_idx'), models.Index(fields=['author', '-created_at'], name='lists_list_author__c5b92a_idx'), models.Index(fields=['submitted_by', '-created_at'], name='lists_list_submitt_7322b3_idx'), models.Index(fields=['-updated_at'], name='lists_list_updated_a8b942_idx')],
                'constraints': [models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='lists_list_slug_sponsor_unique')],
            },
        ),
    ]
