# Generated by Django 5.2.8 on 2026-02-05 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItemAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_text_hash', models.CharField(db_index=True, help_text='SHA-256 hash of normalized item text for matching', max_length=64)),
                ('item_text_snapshot', models.CharField(help_text='Original item text at promotion time', max_length=500)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='lists.list')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_list_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='The Project task created from this list item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_annotations', to='projects.task')),
            ],
            options={
                'verbose_name': 'List Item Annotation',
                'verbose_name_plural': 'List Item Annotations',
                'indexes': [models.Index(fields=['list', 'item_text_hash'], name='lists_listi_list_id_874171_idx')],
            },
        ),
    ]
