# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loose_title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_title', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_author', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('node_count', models.IntegerField(blank=True, null=True)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('embedding_model', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('summary', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtoAgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_list', models.JSONField()),
                ('books_per_agent', models.IntegerField(default=10)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StartupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='started', max_length=20)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(default='gutenberg', max_length=64)),
                ('asset_type', models.CharField(default='book', max_length=32)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('author', models.CharField(blank=True, max_length=512, null=True)),
                ('subject_tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('retrieved', models.BooleanField(default=False)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('synopsis_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_status', models.CharField(choices=[('not_started', 'Not Started'), ('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='not_started', max_length=32)),
                ('ingestion_started_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedGutenbergInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.PositiveIntegerField()),
                ('deleted_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gutenberg_info', to='inkwell.deletedasset')),
            ],
        ),
        migrations.CreateModel(
            name='IngestedWebpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('raw_html_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('extracted_text_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpage_info', to='inkwell.ingestedasset')),
            ],
        ),
        migrations.CreateModel(
            name='LLMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('text', models.TextField()),
                ('markdown_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inkwell.llmsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingestedasset',
            name='suggested_asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inkwell.suggestedasset'),
        ),
        migrations.AddField(
            model_name='deletedasset',
            name='suggested_asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_asset', to='inkwell.suggestedasset'),
        ),
        migrations.CreateModel(
            name='DeclinedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declined_asset', to='inkwell.suggestedasset')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedGutenbergInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_url', models.URLField(blank=True, null=True)),
                ('gutenberg_id', models.PositiveIntegerField()),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gutenberg_info', to='inkwell.suggestedasset')),
            ],
        ),
        migrations.CreateModel(
            name='IngestedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filehash', models.CharField(max_length=128)),
                ('filepath', models.CharField(max_length=1024)),
                ('file_type', models.CharField(choices=[('txt', 'Text'), ('pdf', 'PDF')], default='txt', max_length=16)),
                ('collection_name', models.CharField(max_length=255)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_info', to='inkwell.ingestedasset')),
            ],
            options={
                'indexes': [models.Index(fields=['filehash', 'collection_name'], name='inkwell_ing_filehas_eb8c80_idx')],
                'unique_together': {('filehash', 'collection_name')},
            },
        ),
    ]
