# Generated by Django 5.2.8 on 2025-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkwell', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingestedfile',
            new_name='inkwell_ing_filehas_eb8c80_idx',
            old_name='inkwell_ingested_filehas_e4fd96_idx',
        ),
    ]
