# Generated by Django 5.2.8 on 2026-10-03 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('folio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], max_length=16)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('transcript_model', models.CharField(blank=True, default='', max_length=64)),
                ('transcript_backend', models.CharField(blank=True, default='', max_length=32)),
                ('transcript_created_at', models.DateTimeField(blank=True, null=True)),
                ('transcript_error', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('suggested_shape', models.CharField(blank=True, choices=[('character', 'Character'), ('scene', 'Scene'), ('plot', 'Plot'), ('place', 'Place'), ('world', 'World'), ('meta', 'Meta'), ('unplaced', 'Unplaced')], default='', max_length=32)),
                ('shape_confidence', models.FloatField(blank=True, null=True)),
                ('confirmed_shape', models.CharField(blank=True, choices=[('character', 'Character'), ('scene', 'Scene'), ('plot', 'Plot'), ('place', 'Place'), ('world', 'World'), ('meta', 'Meta'), ('unplaced', 'Unplaced')], default='', max_length=32)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_notes', to='files.storedfile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folio_notes', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='folio.folio')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['folio', 'created_at'], name='folio_folio_folio_i_fc5ec4_idx')],
            },
        ),
    ]
