# Generated by Django 5.2.8 on 2026-10-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_folio_note'),
        ('initiatives', '0025_alter_aperturelogentry_authored_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='folionote',
            name='mentions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='folionote',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folionote',
            name='tended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folionote',
            name='tending_action_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tended_folio_notes', to='initiatives.actionrun'),
        ),
        migrations.AddField(
            model_name='folionote',
            name='tending_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folionote',
            name='tending_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='folionote',
            name='tending_prompt_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
