# Generated by Django 5.2.8 on 2026-10-06 19:44

from django.db import migrations, models


def rename_place_to_setting(apps, schema_editor):
    FolioNote = apps.get_model('folio', 'FolioNote')
    FolioNote.objects.filter(suggested_shape='place').update(suggested_shape='setting')
    FolioNote.objects.filter(confirmed_shape='place').update(confirmed_shape='setting')
    for note in FolioNote.objects.only('id', 'mentions').iterator(chunk_size=500):
        mentions = note.mentions or []
        changed = False
        for mention in mentions:
            if isinstance(mention, dict) and mention.get('kind') == 'place':
                mention['kind'] = 'setting'
                changed = True
        if changed:
            FolioNote.objects.filter(pk=note.pk).update(mentions=mentions)


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_folio_note_tending'),
    ]

    operations = [
        migrations.RunPython(rename_place_to_setting, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='folionote',
            name='confirmed_shape',
            field=models.CharField(blank=True, choices=[('character', 'Character'), ('scene', 'Scene'), ('plot', 'Plot'), ('setting', 'Setting'), ('world', 'World'), ('meta', 'Meta'), ('unplaced', 'Unplaced')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='folionote',
            name='suggested_shape',
            field=models.CharField(blank=True, choices=[('character', 'Character'), ('scene', 'Scene'), ('plot', 'Plot'), ('setting', 'Setting'), ('world', 'World'), ('meta', 'Meta'), ('unplaced', 'Unplaced')], default='', max_length=32),
        ),
    ]
