# Generated by Django 5.2.8 on 2026-05-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('living_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livingbook',
            new_name='living_book_trunk_i_80ff5e_idx',
            old_name='living_book_trunk_id_idx',
        ),
        migrations.RenameIndex(
            model_name='livingbook',
            new_name='living_book_status_d7a6c2_idx',
            old_name='living_book_status_idx',
        ),
    ]
