# Generated by Django 5.2.8 on 2026-05-28 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_book', '0002_rename_living_book_trunk_id_idx_living_book_trunk_i_80ff5e_idx_and_more'),
        ('writing', '0025_rename_writing_wri_analysi_bbd3b1_idx_writing_wri_analysi_35ea8a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_node_id', models.UUIDField(unique=True)),
                ('prompt_text', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_detached', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('living_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='living_book.livingbook')),
                ('parent_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_branches', to='living_book.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeafCluster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video')], default='text', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_clusters', to='living_book.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leaf_clusters', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_cluster_memberships', to='writing.writingpiece')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['living_book'], name='branch_living_book_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['anchor_node_id'], name='branch_anchor_node_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcluster',
            index=models.Index(fields=['branch'], name='leafcluster_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcluster',
            index=models.Index(fields=['piece'], name='leafcluster_piece_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leafcluster',
            unique_together={('branch', 'piece')},
        ),
    ]
