# Generated by Django 5.2.8 on 2026-05-28 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_object_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recurrence_rule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly')], max_length=64)),
                ('next_due_at', models.DateTimeField()),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('suggested_verb', models.CharField(blank=True, max_length=64)),
                ('suggested_context', models.JSONField(blank=True, default=dict)),
                ('suggested_label', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['next_due_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'next_due_at'], name='recurring_a_is_acti_a396d5_idx'), models.Index(fields=['content_type', 'owner_object_id'], name='recurring_a_content_30fc47_idx')],
            },
        ),
    ]
