# Generated by Django 5.2.8 on 2026-03-20 20:55

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0009_admission_policy_to_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBroadcast',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list, size=None)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When null, fires immediately on status → queued.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='groups.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_deliveries', to=settings.AUTH_USER_MODEL)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='broadcast.groupbroadcast')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastAudience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('all_members', 'All Members'), ('role', 'By Role'), ('custom', 'Custom User List')], max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('user_ids', models.JSONField(blank=True, default=list)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='broadcast.groupbroadcast')),
            ],
        ),
        migrations.CreateModel(
            name='UserBroadcastPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_in_app', models.BooleanField(default=True)),
                ('allow_email', models.BooleanField(default=False)),
                ('allow_sms', models.BooleanField(default=False)),
                ('sms_verified', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, help_text='null = global default across all groups', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_broadcast_preferences', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='groupbroadcast',
            index=models.Index(fields=['group', 'status'], name='broadcast_g_group_i_8c01e6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupbroadcast',
            index=models.Index(fields=['status', 'scheduled_at'], name='broadcast_g_status_4aaa79_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastdelivery',
            index=models.Index(fields=['broadcast', 'status'], name='broadcast_b_broadca_be9d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastdelivery',
            index=models.Index(fields=['user', 'channel'], name='broadcast_b_user_id_c4910c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastdelivery',
            unique_together={('broadcast', 'user', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='userbroadcastpreferences',
            unique_together={('user', 'group')},
        ),
    ]
