# Generated by Django 5.2.8 on 2026-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbroadcast',
            name='lm_campaign_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
