# Generated by Django 5.2.8 on 2026-01-17 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fundamentals', '0001_initial'),
        ('stackroom', '0012_puddlejump_personal_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_object_id', models.UUIDField()),
                ('title', models.CharField(blank=True, default='', help_text='Optional title for the recording', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or notes')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='When the audio was originally recorded (if known)', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('interpreting', 'Interpreting'), ('ready', 'Ready for Review'), ('accepted', 'Accepted'), ('promoted', 'Promoted'), ('archived', 'Archived'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, help_text='Last time status changed')),
                ('audio_path', models.CharField(blank=True, default='', help_text='Direct S3 key for the audio file', max_length=512)),
                ('audio_content_type', models.CharField(blank=True, default='', help_text='MIME type of the audio file (e.g., audio/mpeg)', max_length=100)),
                ('audio_size_bytes', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When transcription processing began', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='When processing completed (success or failure)', null=True)),
                ('processing_error', models.TextField(blank=True, default='', help_text='Error message if processing failed')),
                ('asset', models.ForeignKey(blank=True, help_text='Reference to the audio file as an Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='assets.asset')),
                ('created_by', models.ForeignKey(help_text='User who uploaded/created this recording', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recordings', to=settings.AUTH_USER_MODEL)),
                ('mill_draft', models.ForeignKey(blank=True, help_text='MillDraft created from this recording', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_recordings', to='fundamentals.milldraft')),
                ('source_file', models.ForeignKey(blank=True, help_text='Reference to the audio file in Stackroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='stackroom.sourcefile')),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_recordings', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='concord_rec_sponsor_f79f0d_idx'), models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'status'], name='concord_rec_sponsor_4fb58d_idx'), models.Index(fields=['status', '-created_at'], name='concord_rec_status_ae368e_idx'), models.Index(fields=['created_by', '-created_at'], name='concord_rec_created_6b3d69_idx')],
            },
        ),
    ]
