# Generated by Django 5.2.8 on 2026-01-17 23:28

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
        ('concord', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fundamentals', '0001_initial'),
        ('stackroom', '0012_puddlejump_personal_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recording',
            name='concord_rec_sponsor_4fb58d_idx',
        ),
        migrations.RemoveIndex(
            model_name='recording',
            name='concord_rec_created_6b3d69_idx',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='description',
        ),
        migrations.AddField(
            model_name='recording',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recording',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recording',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recording',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='slug',
            field=models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='recording',
            name='slug_history',
            field=models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).'),
        ),
        migrations.AddField(
            model_name='recording',
            name='slug_is_custom',
            field=models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.'),
        ),
        migrations.AddField(
            model_name='recording',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recording',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='sponsor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='concord_rec_sponsor_b11884_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['author', '-created_at'], name='concord_rec_author__4d17a4_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['submitted_by', '-created_at'], name='concord_rec_submitt_e45568_idx'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='concord_recording_slug_sponsor_unique'),
        ),
    ]
