# Generated by Django 5.2.8 on 2026-01-18 03:26

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
        ('concord', '0002_remove_recording_concord_rec_sponsor_4fb58d_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fundamentals', '0001_initial'),
        ('groups', '0002_initial'),
        ('stackroom', '0012_puddlejump_personal_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerAnchor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_label', models.CharField(help_text="Self-asserted name: 'This is Mark speaking'", max_length=100)),
                ('sample_start_ms', models.PositiveIntegerField(blank=True, help_text='Start position of voice sample in source recording', null=True)),
                ('sample_end_ms', models.PositiveIntegerField(blank=True, help_text='End position of voice sample in source recording', null=True)),
                ('embedding', models.BinaryField(blank=True, help_text='Voice embedding vector (format TBD by model)', null=True)),
                ('embedding_model', models.CharField(blank=True, default='', help_text='Model used to generate embedding', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence in this anchor (0.0-1.0)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this anchor should be used for matching')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, help_text='Transcription version (for re-processing)')),
                ('text', models.TextField(blank=True, default='', help_text='Full transcription text')),
                ('language', models.CharField(blank=True, default='', help_text="Detected or specified language code (e.g., 'en')", max_length=10)),
                ('confidence_avg', models.FloatField(blank=True, help_text='Average confidence score across segments', null=True)),
                ('whisper_model', models.CharField(blank=True, default='', help_text="Whisper model used (e.g., 'large-v3')", max_length=50)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_index', models.PositiveIntegerField(help_text='0-based index within transcription')),
                ('start_ms', models.PositiveIntegerField(help_text='Start time in milliseconds')),
                ('end_ms', models.PositiveIntegerField(help_text='End time in milliseconds')),
                ('text', models.TextField(help_text='Segment text content')),
                ('speaker_label', models.CharField(blank=True, default='', help_text="Speaker label (from anchor or fallback 'Speaker A')", max_length=100)),
                ('speaker_confidence', models.FloatField(blank=True, help_text='Confidence in speaker attribution (0.0-1.0)', null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Transcription confidence for this segment', null=True)),
            ],
            options={
                'ordering': ['transcription', 'segment_index'],
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='is_voice_sample',
            field=models.BooleanField(default=False, help_text='True if this is a speaker identification sample'),
        ),
        migrations.AddField(
            model_name='recording',
            name='segment_index',
            field=models.PositiveIntegerField(blank=True, help_text='0-based index within session (part-01 = 0)', null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='track_type',
            field=models.CharField(choices=[('mixed', 'Mixed Audio'), ('microphone', 'Microphone Only'), ('system', 'System Audio Only'), ('speaker_sample', 'Speaker Voice Sample')], default='mixed', help_text='Type of audio track', max_length=20),
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('external_call_id', models.CharField(blank=True, default='', help_text='External identifier (e.g., Zoom meeting ID)', max_length=255)),
                ('session_started_at', models.DateTimeField(blank=True, help_text='When the session/call actually started', null=True)),
                ('session_ended_at', models.DateTimeField(blank=True, help_text='When the session/call ended', null=True)),
                ('segment_duration_seconds', models.PositiveIntegerField(default=900, help_text='Target segment duration in seconds')),
                ('expected_participants', models.JSONField(blank=True, default=list, help_text='List of expected participant names/identifiers')),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('completed', 'Completed'), ('processing', 'Processing'), ('ready', 'Ready'), ('archived', 'Archived')], db_index=True, default='recording', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recording Session',
                'verbose_name_plural': 'Recording Sessions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Parent session for segmented recordings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='concord.recordingsession'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['session', 'segment_index'], name='concord_rec_session_e4f633_idx'),
        ),
        migrations.AddField(
            model_name='speakeranchor',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group this anchor is scoped to (for cross-session use)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_anchors', to='groups.group'),
        ),
        migrations.AddField(
            model_name='speakeranchor',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session this anchor is scoped to (if session-specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_anchors', to='concord.recordingsession'),
        ),
        migrations.AddField(
            model_name='speakeranchor',
            name='source_recording',
            field=models.ForeignKey(blank=True, help_text='Recording containing the voice sample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_anchors', to='concord.recording'),
        ),
        migrations.AddField(
            model_name='speakeranchor',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Mixtape user if speaker is a known member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_anchors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcription',
            name='recording',
            field=models.ForeignKey(help_text='Recording this transcription is derived from', on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='concord.recording'),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='speaker_anchor',
            field=models.ForeignKey(blank=True, help_text='Matched speaker anchor (if identified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_segments', to='concord.speakeranchor'),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='transcription',
            field=models.ForeignKey(help_text='Parent transcription', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='concord.transcription'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='concord_rec_sponsor_589c85_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='concord_rec_sponsor_1acd41_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['author', '-created_at'], name='concord_rec_author__c1e6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingsession',
            index=models.Index(fields=['submitted_by', '-created_at'], name='concord_rec_submitt_cba905_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordingsession',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='concord_recordingsession_slug_sponsor_unique'),
        ),
        migrations.AddIndex(
            model_name='speakeranchor',
            index=models.Index(fields=['session', 'speaker_label'], name='concord_spe_session_c57974_idx'),
        ),
        migrations.AddIndex(
            model_name='speakeranchor',
            index=models.Index(fields=['group', 'speaker_label'], name='concord_spe_group_i_fa87f3_idx'),
        ),
        migrations.AddIndex(
            model_name='speakeranchor',
            index=models.Index(fields=['user'], name='concord_spe_user_id_5489ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='speakeranchor',
            constraint=models.CheckConstraint(condition=models.Q(('session__isnull', False), ('group__isnull', False), _connector='OR'), name='speaker_anchor_must_have_scope'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['recording', 'version'], name='concord_tra_recordi_2a1650_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transcription',
            unique_together={('recording', 'version')},
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['transcription', 'segment_index'], name='concord_tra_transcr_45c0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['speaker_anchor'], name='concord_tra_speaker_717e3c_idx'),
        ),
    ]
