# Generated by Django 5.2.8 on 2026-04-29 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_object_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_suppliers', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_object_id', models.UUIDField()),
                ('item_name', models.CharField(max_length=255)),
                ('quantity_note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received')], default='pending', max_length=20)),
                ('initiative_object_id', models.UUIDField(blank=True, null=True)),
                ('raw_input', models.TextField(blank=True, default='')),
                ('parsed_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supply_requests', to=settings.AUTH_USER_MODEL)),
                ('initiative_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_supply_request_initiatives', to='contenttypes.contenttype')),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_supply_requests', to='contenttypes.contenttype')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests', to='business.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sponsor_object_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('initiative_object_id', models.UUIDField(blank=True, null=True)),
                ('raw_input', models.TextField(blank=True, default='')),
                ('parsed_metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fix_items', to=settings.AUTH_USER_MODEL)),
                ('initiative_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_fix_item_initiatives', to='contenttypes.contenttype')),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_fix_items', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['sponsor_content_type', 'sponsor_object_id', '-created_at'], name='business_fixitem_sponsor_idx'), models.Index(fields=['status', '-created_at'], name='business_fixitem_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'name'], name='business_supplier_sponsor_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', '-created_at'], name='business_supplyreq_sponsor_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrequest',
            index=models.Index(fields=['status', '-created_at'], name='business_supplyreq_status_idx'),
        ),
    ]
