# Generated by Django 5.2.8 on 2026-09-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_client_deleted_at'),
        ('groups', '0037_alter_group_in_crossroads_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='groups.group'),
        ),
    ]
