# Generated by Django 5.2.8 on 2026-08-25 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantClaudeRuntime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_object_id', models.UUIDField()),
                ('provider', models.CharField(default='anthropic-claude-code', help_text='AI runtime provider identifier.', max_length=64)),
                ('linux_user', models.CharField(help_text='Linux username under which Claude subprocesses run (e.g. tob-catalyst).', max_length=64)),
                ('home_dir', models.CharField(help_text='Absolute home directory for linux_user (e.g. /home/tob-catalyst).', max_length=256)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('login_required', 'Login required'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='not_configured', max_length=32)),
                ('privacy_mode', models.CharField(choices=[('local_only', 'Local only'), ('escalation_allowed', 'Escalation allowed')], default='local_only', max_length=32)),
                ('allowed_ai_modes', models.JSONField(default=list, help_text='Permitted AI operation types for this tenant, e.g. ["extraction", "shaping"].')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verification_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Tenant Claude Runtime',
                'verbose_name_plural': 'Tenant Claude Runtimes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantClaudeLoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('awaiting_auth', 'Awaiting auth'), ('complete', 'Complete'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='starting', max_length=32)),
                ('login_url', models.TextField(blank=True, default='', help_text='Login URL extracted from subprocess stdout — displayed to admin, never secret.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='tenant_runtime.tenantclauderuntime')),
            ],
            options={
                'verbose_name': 'Tenant Claude Login Session',
                'verbose_name_plural': 'Tenant Claude Login Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
