# Generated by Codex on 2026-09-03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenant_runtime", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantCodexRuntime",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_object_id", models.UUIDField()),
                ("provider", models.CharField(default="openai-codex", help_text="AI runtime provider identifier.", max_length=64)),
                ("linux_user", models.CharField(help_text="Linux username under which Codex subprocesses run.", max_length=64)),
                ("home_dir", models.CharField(help_text="Absolute home directory for linux_user.", max_length=256)),
                ("provider_home_dir", models.CharField(blank=True, default="", help_text="CODEX_HOME directory. Defaults to <home_dir>/.codex when blank.", max_length=256)),
                ("auth_method", models.CharField(choices=[("chatgpt", "ChatGPT"), ("api_key", "API key"), ("access_token", "Access token")], default="chatgpt", help_text="Declared Codex auth mode; credentials are not stored here.", max_length=32)),
                ("status", models.CharField(choices=[("not_configured", "Not configured"), ("login_required", "Login required"), ("ready", "Ready"), ("failed", "Failed")], db_index=True, default="not_configured", max_length=32)),
                ("privacy_mode", models.CharField(choices=[("local_only", "Local only"), ("escalation_allowed", "Escalation allowed")], default="local_only", max_length=32)),
                ("allowed_ai_modes", models.JSONField(default=list, help_text='Permitted AI operation types for this tenant, e.g. ["atrium", "extraction"].')),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_verification_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="contenttypes.contenttype")),
            ],
            options={
                "verbose_name": "Tenant Codex Runtime",
                "verbose_name_plural": "Tenant Codex Runtimes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantCodexLoginSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("starting", "Starting"), ("awaiting_auth", "Awaiting auth"), ("complete", "Complete"), ("failed", "Failed"), ("expired", "Expired")], db_index=True, default="starting", max_length=32)),
                ("login_url", models.TextField(blank=True, default="")),
                ("login_code", models.CharField(blank=True, default="", max_length=128)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("runtime", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="login_sessions", to="tenant_runtime.tenantcodexruntime")),
            ],
            options={
                "verbose_name": "Tenant Codex Login Session",
                "verbose_name_plural": "Tenant Codex Login Sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
