# Generated by Django 5.2.8 on 2026-04-19 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('business_type', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=200)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('intake_started', 'Intake Started'), ('meeting_scheduled', 'Meeting Scheduled'), ('proposal_stage', 'Proposal Stage'), ('won', 'Won'), ('lost', 'Lost'), ('archived', 'Archived')], default='new', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('converted_to_group_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question_kind', models.CharField(choices=[('long_text', 'Long Text'), ('voice_or_text', 'Voice or Text'), ('structured_followup', 'Structured Followup')], default='long_text', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ProspectIntakeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('pre_meeting', 'Pre-Meeting'), ('guided_live', 'Guided Live'), ('hybrid', 'Hybrid')], default='pre_meeting', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('access_mode', models.CharField(choices=[('token_only', 'Token Only'), ('authenticated', 'Authenticated')], default='token_only', max_length=20)),
                ('resume_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('notify_on_submit', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intake_sessions', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='prospects.businessprospect')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('human', 'Human'), ('ai_assisted', 'AI Assisted'), ('ai_generated', 'AI Generated')], default='human', max_length=20)),
                ('kind', models.CharField(choices=[('pain_point', 'Pain Point'), ('opportunity', 'Opportunity'), ('canon_domain', 'Canon Domain'), ('tone_signal', 'Tone Signal'), ('followup_question', 'Followup Question')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insights', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='prospects.businessprospect')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='prospects.prospectintakesession')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_notes', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='prospects.businessprospect')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='prospects.prospectintakesession')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_prompt_snapshot', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('response_mode', models.CharField(choices=[('typed', 'Typed'), ('voice', 'Voice'), ('mixed', 'Mixed')], default='typed', max_length=20)),
                ('human_refined_text', models.TextField(blank=True, null=True)),
                ('ai_summary_text', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='prospects/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='prospects.prospectintakesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='prospects.prospectquestion')),
            ],
            options={
                'unique_together': {('intake_session', 'question')},
            },
        ),
    ]
