# Generated by Django 5.2.8 on 2026-04-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('prospects', '0002_seed_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprospect',
            name='sponsor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_prospects', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='businessprospect',
            name='sponsor_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
