# Generated by Django 5.2.8 on 2026-04-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_businessprospect_sponsor_content_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospectresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prospectresponse',
            name='file_kind',
            field=models.CharField(blank=True, choices=[('md', 'Markdown'), ('pdf', 'PDF'), ('docx', 'Word Document'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='prospectresponse',
            name='kind',
            field=models.CharField(choices=[('typed', 'Typed'), ('file', 'File'), ('voice', 'Voice')], default='typed', max_length=10),
        ),
        migrations.AddField(
            model_name='prospectresponse',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospectresponse',
            name='processing_status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed')], default='done', max_length=15),
        ),
        migrations.AddField(
            model_name='prospectresponse',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='prospects/intake/'),
        ),
        migrations.RemoveField(
            model_name='prospectresponse',
            name='response_mode',
        ),
    ]
