# Generated by Django 5.2.8 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_ec_phase1_prospects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectquestiononboardingmap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
