# Generated by Django 5.2.8 on 2026-08-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0006_alter_prospectquestiononboardingmap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprospect',
            name='knowledge_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprospect',
            name='org_description',
            field=models.TextField(blank=True),
        ),
    ]
