# Generated by Django 5.2.8 on 2026-03-22 03:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('direction', models.TextField(blank=True, default='', help_text='Compass heading — not a scope statement. Optional.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('simmering', 'Simmering'), ('paused', 'Paused'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('sponsor_object_id', models.UUIDField()),
                ('thread_label', models.CharField(blank=True, default='', help_text='Short label for this thread within its parent (v2).', max_length=120)),
                ('rolling_summary', models.JSONField(blank=True, default=dict, help_text='Structured synthesis of all prior sessions. Schema: {current_direction, key_decisions, open_questions, where_we_are_now}')),
                ('rolling_summary_updated_at', models.DateTimeField(blank=True, null=True)),
                ('rolling_summary_updated_by', models.CharField(blank=True, default='', help_text="'ai' or username — tracks who last edited the summary.", max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_initiatives', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent Initiative for thread structure (v2). Null = root initiative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='initiatives.initiative')),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_initiatives', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_agent_tokens', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tokens', to='initiatives.initiative')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedOutput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_object_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Optional human note about the relationship.')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_outputs', to='initiatives.initiative')),
                ('output_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('exploring', 'Exploring'), ('deciding', 'Deciding'), ('reviewing', 'Reviewing'), ('closing', 'Closing')], default='exploring', max_length=20)),
                ('capture_mode', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('imported', 'Imported')], default='text', max_length=20)),
                ('raw_transcript', models.JSONField(blank=True, default=list, help_text='Array of turn objects: [{speaker, username, text, timestamp}]')),
                ('distillation', models.JSONField(blank=True, default=dict, help_text="Schema: {decisions: [], open_questions: [], actions: [], notes: ''}")),
                ('distillation_state', models.CharField(choices=[('pending', 'Pending'), ('proposed', 'Proposed'), ('curated', 'Curated')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_sessions', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='initiatives.initiative')),
            ],
            options={
                'ordering': ['started_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('document', 'Document'), ('decision', 'Decision'), ('question', 'Question'), ('action', 'Action'), ('annotation', 'Annotation')], default='document', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='', help_text='Optional human note — e.g. where this came from for Direct Annotations.')),
                ('quality_scan_result', models.JSONField(blank=True, help_text="Schema: {assessment: 'ok'|'advisory', note: str}", null=True)),
                ('quality_scan_state', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('puddlejump_routed', models.BooleanField(default=False, help_text='Has this been submitted to Puddlejump as a candidate doc?')),
                ('puddlejump_routed_at', models.DateTimeField(blank=True, null=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='initiatives.initiative')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='initiatives.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', '-updated_at'], name='initiatives_sponsor_fe8527_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['status', '-updated_at'], name='initiatives_status_69080e_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['initiative', 'started_at'], name='initiatives_initiat_024eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['initiative', 'distillation_state'], name='initiatives_initiat_038ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['initiative', '-created_at'], name='initiatives_initiat_356736_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['initiative', 'kind'], name='initiatives_initiat_b31a47_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['puddlejump_routed'], name='initiatives_puddlej_76b9ca_idx'),
        ),
    ]
