# Generated by Django 5.2.8 on 2026-04-08 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('initiatives', '0002_threads_handoffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='True for the single Personal Initiative auto-created by MemberStartupService. Prevents the fragile sponsor=user + parent=None match from becoming ambiguous once users can create their own root Initiatives.'),
        ),
        migrations.CreateModel(
            name='ApertureLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_handoff_at', models.DateTimeField(blank=True, help_text="Denormalized — updated on every ApertureLogEntry with kind='handoff'.", null=True)),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aperture_log', to='initiatives.initiative')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApertureLogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('prose', 'Prose'), ('ledger', 'Ledger'), ('handoff', 'Handoff'), ('emph', 'Emphasis'), ('seed_spawn', 'Seed Spawn')], default='prose', max_length=20)),
                ('body', models.TextField(blank=True, default='', help_text='Human-authored content for prose/handoff entries; system description for ledger entries.')),
                ('emph_note', models.TextField(blank=True, default='', help_text='The quoted note from /emph. Blank for all non-emph kinds.')),
                ('ledger_event_type', models.CharField(blank=True, choices=[('session_started', 'Session started'), ('session_ended', 'Session ended'), ('document_bound', 'Document bound'), ('seed_promoted', 'Seed promoted'), ('status_changed', 'Status changed'), ('artifact_linked', 'Artifact linked'), ('material_late_bound', 'Material late-bound')], default='', max_length=40)),
                ('ledger_data', models.JSONField(blank=True, help_text='Structured event payload for ledger entries. Schema varies by ledger_event_type.', null=True)),
                ('spawned_seed_object_id', models.UUIDField(blank=True, null=True)),
                ('emph_is_summary_candidate', models.BooleanField(default=False, help_text='System has proposed this /emph as a rolling summary candidate.')),
                ('emph_accepted_to_summary', models.BooleanField(default=False, help_text='Member accepted this /emph into the rolling summary.')),
                ('is_system_generated', models.BooleanField(default=False, help_text='True for ledger entries and system-appended /emph candidates. Not editable by member.')),
                ('authored_by', models.CharField(blank=True, default='', help_text="username for member entries; 'system' for ledger entries.", max_length=150)),
                ('aperture_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='initiatives.aperturelog')),
                ('created_by', models.ForeignKey(blank=True, help_text='Null for system-generated entries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperture_log_entries', to=settings.AUTH_USER_MODEL)),
                ('spawned_seed_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['aperture_log', 'created_at'], name='initiatives_apertur_1981ae_idx'), models.Index(fields=['aperture_log', 'kind'], name='initiatives_apertur_ad2404_idx'), models.Index(fields=['aperture_log', 'kind', 'emph_is_summary_candidate'], name='initiatives_apertur_fbf1bd_idx')],
            },
        ),
    ]
