# Generated by Django 5.2.8 on 2026-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
