# Generated by Django 5.2.8 on 2026-04-19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0006_alter_reminder_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tool_name", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="pending", max_length=20)),
                ("execution_mode", models.CharField(choices=[("local", "Local"), ("local_retrieval", "Local + Retrieval"), ("cloud", "Cloud")], default="local", max_length=20)),
                ("service_name", models.CharField(default="switchboard", max_length=80)),
                ("tenant_id", models.UUIDField()),
                ("tenant_namespace", models.CharField(max_length=255)),
                ("initiator_type", models.CharField(choices=[("human", "Human"), ("model", "Model"), ("system", "System")], max_length=20)),
                ("initiator_id", models.CharField(max_length=255)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("result_payload", models.JSONField(blank=True, null=True)),
                ("error_payload", models.JSONField(blank=True, null=True)),
                ("cloud_approved", models.BooleanField(default=False)),
                ("approval_payload", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("initiative", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="action_runs", to="initiatives.initiative")),
                ("parent_action", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="child_actions", to="initiatives.actionrun")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="action_runs", to="initiatives.session")),
            ],
            options={
                "ordering": ["-started_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["tenant_namespace", "-started_at"], name="initiatives_ar_tenant_idx"),
                    models.Index(fields=["tool_name", "-started_at"], name="initiatives_ar_tool_idx"),
                    models.Index(fields=["status", "-started_at"], name="initiatives_ar_status_idx"),
                    models.Index(fields=["initiator_type", "initiator_id"], name="initiatives_ar_init_idx"),
                ],
            },
        ),
    ]
