# Generated by Django 5.2.8 on 2026-05-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0014_aperturelogentry_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturelog',
            name='handover_draft',
            field=models.JSONField(blank=True, default=None, help_text='AI-generated handover draft written by handover_task. Cleared after a handoff entry is approved.', null=True),
        ),
    ]
