# Generated by Django 5.2.8 on 2026-05-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0015_handover_draft_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionrun',
            options={'ordering': ['-started_at'], 'permissions': [('approve_cloud_dispatch', 'Can approve cloud AI dispatch')]},
        ),
    ]
