# Generated by Django 5.2.8 on 2026-06-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0018_initiativeartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='member_last_active_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last member-driven action on this initiative. Set by InitiativeService on any member write or workspace open. Never set by system jobs, collaborator actions, or background processes. Radar default sort uses this field, not updated_at.', null=True),
        ),
        migrations.AddField(
            model_name='initiativeartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
