# Generated by Django 5.2.8 on 2026-08-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0019_initiative_member_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturelog',
            name='compact_at',
            field=models.DateTimeField(blank=True, help_text='When the last compact was performed.', null=True),
        ),
        migrations.AddField(
            model_name='aperturelog',
            name='compact_summary',
            field=models.TextField(blank=True, help_text='Compact summary produced by /compact in the Atrium PTY session. Injected as opening context on reconnect.', null=True),
        ),
        migrations.AddField(
            model_name='aperturelog',
            name='last_session_end',
            field=models.DateTimeField(blank=True, help_text='When the last Atrium PTY session was terminated for this initiative.', null=True),
        ),
    ]
