# Generated by Django 5.2.8 on 2026-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0022_aperturelog_import_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturelog',
            name='compact_summary',
            field=models.TextField(blank=True, help_text='Compact summary produced by the Continuous Keeper. Injected as opening context on cold spawn.', null=True),
        ),
        migrations.AlterField(
            model_name='aperturelog',
            name='last_session_end',
            field=models.DateTimeField(blank=True, help_text='When the last Atrium session was terminated for this initiative.', null=True),
        ),
        migrations.AlterField(
            model_name='aperturelogentry',
            name='authored_by',
            field=models.CharField(blank=True, default='', help_text="username for member entries; 'system' for ledger entries; 'claude' for imported AI turns.", max_length=150),
        ),
        migrations.AddField(
            model_name='aperturelogentry',
            name='source_timestamp',
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                help_text='Original timestamp of an imported conversation turn. Null for native entries.',
            ),
        ),
    ]
