# Generated by Django 5.2.8 on 2026-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0024_actionrun_source_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturelogentry',
            name='authored_by',
            field=models.CharField(blank=True, default='', help_text="username for member entries; 'system' for ledger entries; the lowercased AI platform name (e.g. 'claude', 'chatgpt') for imported AI turns.", max_length=150),
        ),
    ]
