# Generated by Django 5.2.8 on 2026-06-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprig', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sprig',
            new_name='sprig_sprig_author__41ec41_idx',
            old_name='sprig_sprig_author__status_idx',
        ),
        migrations.RenameIndex(
            model_name='sprig',
            new_name='sprig_sprig_sponsor_bebb10_idx',
            old_name='sprig_sprig_sponsor_status_idx',
        ),
    ]
