# Generated by Django 5.2.8 on 2026-02-21 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_path', models.CharField(max_length=512)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.BigIntegerField(default=0)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['file_type'], name='files_store_file_ty_0233f9_idx'), models.Index(fields=['uploaded_by'], name='files_store_uploade_4538d0_idx')],
            },
        ),
    ]
