# Generated by Django 5.2.8 on 2025-12-22 22:27

import django.db.models.deletion
import fundamentals.models
import fundamentals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Cached count of how many items use this classification')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color code for display (e.g., #FF5733)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Cached count of how many items use this classification')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color code for display (e.g., #FF5733)', max_length=7)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassificationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('classification_client_object_id', models.CharField(db_index=True, max_length=255)),
                ('classification_object_id', models.PositiveIntegerField(db_index=True)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('classification_client_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('classification_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_type', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Classification Usage',
                'verbose_name_plural': 'Classification Usages',
                'indexes': [models.Index(fields=['classification_client_content_type', 'classification_client_object_id'], name='classif_client_idx'), models.Index(fields=['classification_content_type', 'classification_object_id'], name='classif_idx'), models.Index(fields=['classification_client_content_type', 'classification_client_object_id', 'classification_content_type'], name='classif_combined_idx')],
                'unique_together': {('classification_client_content_type', 'classification_client_object_id', 'classification_content_type', 'classification_object_id')},
            },
            bases=(models.Model, fundamentals.validators.AllowedContentTypesMixin),
        ),
    ]
