# Generated by Django 5.2.8 on 2025-12-22 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField()),
                ('note', models.TextField(blank=True, help_text="e.g., 'v2.0 release', 'hotfix for typo'")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_groups', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Publication Group',
                'verbose_name_plural': 'Publication Groups',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentPlacement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField()),
                ('target_object_id', models.UUIDField()),
                ('channel', models.CharField(choices=[('feed', 'Feed'), ('lantern', 'Newsletter'), ('forum', 'Forum'), ('dispatch', 'Dispatch'), ('almanac', 'Events'), ('page', 'Page')], max_length=50)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('private', 'Private'), ('scheduled', 'Scheduled')], max_length=20)),
                ('follow_updates', models.BooleanField(default=False, help_text='If True, display updates when source creates new artifacts. If False, locked to specific artifact.')),
                ('locked_artifact_object_id', models.UUIDField(blank=True, null=True)),
                ('is_excerpt', models.BooleanField(default=False)),
                ('fragment_selector', models.JSONField(blank=True, help_text='Future: specify which content fragments to show', null=True)),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='Override title, excerpt, cover, etc. Keys: title, excerpt, subject, cover_image')),
                ('locked_artifact_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_placements', to='contenttypes.contenttype')),
                ('placed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_placements', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_placements', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_placements', to='contenttypes.contenttype')),
                ('publication_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='publishing.publicationgroup')),
            ],
            options={
                'verbose_name': 'Content Placement',
                'verbose_name_plural': 'Content Placements',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['source_content_type', 'source_object_id'], name='publishing__source__b1655d_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='publishing__target__149f9c_idx'), models.Index(fields=['channel', 'visibility'], name='publishing__channel_379df9_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id', 'channel'), name='unique_placement')],
            },
        ),
    ]
