# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField()),
                ('note', models.TextField(blank=True, help_text="e.g., 'v2.0 release', 'hotfix for typo'")),
            ],
            options={
                'verbose_name': 'Publication Group',
                'verbose_name_plural': 'Publication Groups',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentPlacement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField()),
                ('target_object_id', models.UUIDField()),
                ('channel', models.CharField(choices=[('feed', 'Feed'), ('lantern', 'Newsletter'), ('forum', 'Forum'), ('dispatch', 'Dispatch'), ('almanac', 'Events'), ('page', 'Page')], max_length=50)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('private', 'Private'), ('scheduled', 'Scheduled')], max_length=20)),
                ('follow_updates', models.BooleanField(default=False, help_text='If True, display updates when source creates new artifacts. If False, locked to specific artifact.')),
                ('locked_artifact_object_id', models.UUIDField(blank=True, null=True)),
                ('is_excerpt', models.BooleanField(default=False)),
                ('fragment_selector', models.JSONField(blank=True, help_text='Future: specify which content fragments to show', null=True)),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='Override title, excerpt, cover, etc. Keys: title, excerpt, subject, cover_image')),
                ('locked_artifact_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_placements', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Placement',
                'verbose_name_plural': 'Content Placements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
