# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('publishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplacement',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentplacement',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_placements', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentplacement',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_placements', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationgroup',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contentplacement',
            name='publication_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='publishing.publicationgroup'),
        ),
        migrations.AddIndex(
            model_name='contentplacement',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='publishing__source__b1655d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentplacement',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='publishing__target__149f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentplacement',
            index=models.Index(fields=['channel', 'visibility'], name='publishing__channel_379df9_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentplacement',
            constraint=models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id', 'channel'), name='unique_placement'),
        ),
    ]
