# Generated by Django 5.2.8 on 2026-02-02 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('publishing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentplacement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('follow_updates', True), ('locked_artifact_content_type__isnull', True), ('locked_artifact_object_id__isnull', True)), models.Q(('follow_updates', False), ('locked_artifact_content_type__isnull', False), ('locked_artifact_object_id__isnull', False)), _connector='OR'), name='placement_valid_state'),
        ),
        migrations.AddConstraint(
            model_name='contentplacement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('locked_artifact_content_type__isnull', True), ('locked_artifact_object_id__isnull', True)), models.Q(('locked_artifact_content_type__isnull', False), ('locked_artifact_object_id__isnull', False)), _connector='OR'), name='placement_lock_fields_both_null_or_set'),
        ),
    ]
