# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0003_contentplacement_placement_valid_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentplacement",
            name="channel",
            field=models.CharField(
                choices=[
                    ("feed", "Feed"),
                    ("shelf", "Shelf"),
                    ("lantern", "Newsletter"),
                    ("forum", "Forum"),
                    ("dispatch", "Dispatch"),
                    ("almanac", "Events"),
                    ("page", "Page"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contentplacement",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members Only"),
                    ("unlisted", "Unlisted"),
                    ("private", "Private"),
                    ("scheduled", "Scheduled"),
                ],
                max_length=20,
            ),
        ),
    ]
