# Generated by Django 5.2.8 on 2025-12-22 22:50

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingPiece',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('body_json', models.JSONField(default=dict, help_text='TipTap/ProseMirror content')),
                ('writing_kind', models.CharField(choices=[('post', 'Post'), ('article', 'Article'), ('dispatch', 'Dispatch'), ('forum', 'Forum Post'), ('announcement', 'Announcement'), ('almanac', 'Almanac'), ('page', 'Page'), ('other', 'Other')], default='post', max_length=20)),
                ('current_version_no', models.PositiveIntegerField(default=1)),
                ('is_empty', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('reading_time', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('pinned_rank', models.IntegerField(blank=True, null=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned_at', '-published_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WritingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='writing.writingcomment')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='writing.writingpiece')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('body_json', models.JSONField(default=dict)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('auto_save_count', models.PositiveIntegerField(default=0)),
                ('client_session_id', models.CharField(blank=True, max_length=64)),
                ('dispatch_content', models.ForeignKey(blank=True, help_text='If set, this draft uses Yjs collaborative editing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_documents', to='dispatch.dispatchcontent')),
                ('user', models.ForeignKey(help_text='The user editing this draft', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_copies', to='writing.writingpiece')),
            ],
            options={
                'verbose_name': 'Working Document',
                'verbose_name_plural': 'Working Documents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_uuid', models.UUIDField(unique=True)),
                ('folder_path', models.CharField(blank=True, max_length=500)),
                ('is_primary_source', models.BooleanField(default=True, help_text='Is this the main doc, or a placement/excerpt?')),
                ('collaboration_enabled', models.BooleanField(default=True)),
                ('piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_fields', to='writing.writingpiece')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='articles/heroes/')),
                ('toc_enabled', models.BooleanField(default=True)),
                ('layout_style', models.CharField(choices=[('standard', 'Standard'), ('feature', 'Feature'), ('minimal', 'Minimal')], default='standard', max_length=20)),
                ('series_id', models.UUIDField(blank=True, null=True)),
                ('piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_fields', to='writing.writingpiece')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_line', models.CharField(max_length=255)),
                ('list_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True)),
                ('send_state', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('open_rate', models.FloatField(blank=True, null=True)),
                ('click_rate', models.FloatField(blank=True, null=True)),
                ('piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_fields', to='writing.writingpiece')),
            ],
        ),
        migrations.CreateModel(
            name='WritingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(default='snapshot', help_text="Semantic type: 'snapshot', 'release', 'issue', 'version'", max_length=50)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('body_json', models.JSONField(help_text='Immutable snapshot of published content')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('changelog', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('writing_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='writing.writingpiece')),
            ],
            options={
                'verbose_name': 'Writing Version',
                'verbose_name_plural': 'Writing Versions',
                'ordering': ['-version_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_text', models.TextField(blank=True, default='')),
                ('context_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to=settings.AUTH_USER_MODEL)),
                ('promoted_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_origin', to='writing.workingdocument')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['author', 'updated_at'], name='writing_see_author__e54793_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='writing.writingcomment')),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.AddIndex(
            model_name='writingpiece',
            index=models.Index(fields=['writing_kind'], name='writing_wri_writing_443bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpiece',
            index=models.Index(fields=['status', 'published_at'], name='writing_wri_status_1c6c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpiece',
            index=models.Index(fields=['scheduled_for'], name='writing_wri_schedul_1c74d3_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpiece',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'pinned_at'], name='writing_wri_sponsor_6659df_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpiece',
            index=models.Index(fields=['pinned_at'], name='writing_wri_pinned__7a5ed8_idx'),
        ),
        migrations.AddConstraint(
            model_name='writingpiece',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='published_requires_published_at'),
        ),
        migrations.AddConstraint(
            model_name='writingpiece',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scheduled_for__isnull', False), ('status', 'scheduled')), models.Q(('status', 'scheduled'), _negated=True), _connector='OR'), name='scheduled_requires_scheduled_for'),
        ),
        migrations.AddIndex(
            model_name='workingdocument',
            index=models.Index(fields=['piece', 'user'], name='writing_wor_piece_i_dc721a_idx'),
        ),
        migrations.AddIndex(
            model_name='workingdocument',
            index=models.Index(fields=['last_saved_at'], name='writing_wor_last_sa_eee07a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workingdocument',
            unique_together={('piece', 'user')},
        ),
        migrations.AddIndex(
            model_name='writingversion',
            index=models.Index(fields=['writing_piece', 'version_number'], name='writing_wri_writing_88fbe8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='writingversion',
            unique_together={('writing_piece', 'version_number')},
        ),
    ]
