# Generated by Django 5.2.8 on 2026-02-02 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='writingversion',
            name='sequence_no',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writingversion',
            name='version_label',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='writingversion',
            unique_together={('writing_piece', 'sequence_no')},
        ),
        migrations.RemoveIndex(
            model_name='writingversion',
            name='writing_wri_writing_88fbe8_idx',
        ),
        migrations.AddIndex(
            model_name='writingversion',
            index=models.Index(fields=['writing_piece', 'sequence_no'], name='writing_wri_writing_0c5475_idx'),
        ),
        migrations.RemoveField(
            model_name='writingversion',
            name='version_number',
        ),
        migrations.AlterModelOptions(
            name='writingversion',
            options={'ordering': ['-sequence_no'], 'verbose_name': 'Writing Version', 'verbose_name_plural': 'Writing Versions'},
        ),
    ]
