# Generated by Django 5.2.8 on 2026-02-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_writingversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingpiece',
            name='addressed_to',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
