# Generated by Django 5.2.8 on 2026-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_alter_writingpiece_addressed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingpiece',
            name='enable_outline',
            field=models.BooleanField(default=False, help_text='Opt-in: enable Dispatch outline/section navigator for this piece'),
        ),
    ]
