# Generated by Django 5.2.8 on 2026-02-21 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '__first__'),
        ('writing', '0005_writingpiece_enable_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_seeds', to='files.storedfile'),
        ),
        migrations.AddField(
            model_name='seed',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=16),
        ),
        migrations.AddField(
            model_name='seed',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('failed', 'Failed')], default='ready', max_length=16),
        ),
        migrations.AddField(
            model_name='seed',
            name='transcript_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='transcript_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='transcript_provider',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
