# Generated by Django 5.2.8 on 2026-02-21 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_seed_audio_file_seed_kind_seed_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(default='docx', help_text='Import source format: docx, md, etc.', max_length=32)),
                ('source_sha256', models.CharField(db_index=True, help_text='SHA-256 hash of the source file for idempotency', max_length=64)),
                ('original_filename', models.CharField(max_length=512)),
                ('source_url', models.URLField(blank=True, help_text='Original document URL (e.g. Google Docs link)', null=True)),
                ('import_notes', models.JSONField(blank=True, default=dict, help_text='Extracted comments, warnings, stats from import')),
                ('created_writing_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_receipts', to='writing.writingpiece')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['source_sha256'], name='writing_imp_source__739f1f_idx'), models.Index(fields=['source_type'], name='writing_imp_source__2a0db6_idx')],
            },
        ),
    ]
