# Generated by Django 5.2.8 on 2026-02-26 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0001_initial'),
        ('writing', '0010_seed_transcript_backend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_json', models.JSONField(default=dict, help_text='ProseMirror content for rich text + images')),
                ('caption', models.TextField(blank=True, default='', help_text="Author's original commentary (especially for reference Leafs)")),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link'), ('voice', 'Voice')], default='text', max_length=16)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_preview', models.JSONField(blank=True, default=dict, help_text='Cached link preview metadata (title, image, description)')),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_leaves', to='files.storedfile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_leaves', to='files.storedfile')),
                ('origin_seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_leaves', to='writing.seed')),
                ('promoted_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_origin', to='writing.workingdocument')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeafComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_comments', to=settings.AUTH_USER_MODEL)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='writing.leaf')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='writing.leafcomment')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='leaf',
            index=models.Index(fields=['author', '-published_at'], name='writing_lea_author__836cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaf',
            index=models.Index(fields=['author', 'kind'], name='writing_lea_author__4635bb_idx'),
        ),
    ]
