# Generated by Django 5.2.8 on 2026-03-26 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0011_leaf_leafcomment_leaf_writing_lea_author__836cc6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSynopsis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('teaser', models.TextField(blank=True, help_text='140–220 char compact summary line.')),
                ('description', models.TextField(blank=True, help_text='220–500 char card/preview description.')),
                ('commentary', models.TextField(blank=True, help_text='Optional: 1–3 paragraphs for LinkedIn/social distribution.')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('sponsor_type', models.CharField(blank=True, choices=[('user', 'User'), ('group', 'Group'), ('organization', 'Organization')], max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=16)),
                ('source_version', models.PositiveIntegerField(default=1, help_text='WritingPiece.current_version_no at time of generation.')),
                ('generated_by', models.CharField(choices=[('rule_based', 'Rule-based'), ('ai', 'AI'), ('hybrid', 'Hybrid')], default='rule_based', max_length=16)),
                ('piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synopsis', to='writing.writingpiece')),
            ],
            options={
                'verbose_name': 'Writing Synopsis',
                'verbose_name_plural': 'Writing Synopses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
