# Generated by Django 5.2.8 on 2026-04-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0018_writingsynopsis_linkedin_copy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leafplacementreaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='leafplacement',
            new_name='writing_lea_target__2fc724_idx',
            old_name='writing_lea_target__idx',
        ),
        migrations.RenameIndex(
            model_name='leafplacementreaction',
            new_name='writing_lea_placeme_8b69ca_idx',
            old_name='writing_lea_placeme_reaction_idx',
        ),
        migrations.RenameIndex(
            model_name='seeddispatch',
            new_name='writing_see_seed_id_0e1218_idx',
            old_name='writing_seeddispatch_seed_dest_idx',
        ),
        migrations.AlterField(
            model_name='leafplacement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leafplacementreaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='seeddispatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
