# Generated by Django 5.2.8 on 2026-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0022_writingsuggestedrevision'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='writinganalysissession',
            new_name='writing_wri_source__18a8ff_idx',
            old_name='writing_wri_source__17e638_idx',
        ),
        migrations.RenameIndex(
            model_name='writinganalysissession',
            new_name='writing_wri_status_6da984_idx',
            old_name='writing_wri_status_413bc8_idx',
        ),
        migrations.RenameIndex(
            model_name='writingsuggestedrevision',
            new_name='writing_wri_source__a32097_idx',
            old_name='writing_wri_source__ad2123_idx',
        ),
        migrations.RenameIndex(
            model_name='writingsuggestedrevision',
            new_name='writing_wri_analysi_77890b_idx',
            old_name='writing_wri_analysi_5ab9fb_idx',
        ),
        migrations.RenameIndex(
            model_name='writingsuggestedrevision',
            new_name='writing_wri_source__59cea0_idx',
            old_name='writing_wri_source__2bf4e7_idx',
        ),
        migrations.AddField(
            model_name='writinganalysissession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='writinganalysissession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='writingsuggestedrevision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
