# Generated by Django 5.2.8 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0024_writingfidelityreport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='writingfidelityreport',
            new_name='writing_wri_analysi_35ea8a_idx',
            old_name='writing_wri_analysi_bbd3b1_idx',
        ),
        migrations.RenameIndex(
            model_name='writingfidelityreport',
            new_name='writing_wri_source__5f2682_idx',
            old_name='writing_wri_source__ae3745_idx',
        ),
        migrations.RenameIndex(
            model_name='writingfidelityreport',
            new_name='writing_wri_suggest_a81661_idx',
            old_name='writing_wri_suggest_e2f3b4_idx',
        ),
        migrations.RenameIndex(
            model_name='writingfidelityreport',
            new_name='writing_wri_source__b97a09_idx',
            old_name='writing_wri_source__95b2b0_idx',
        ),
        migrations.AlterField(
            model_name='writingfidelityreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
