# Generated by Django 5.2.8 on 2026-06-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapestry', '0001_initial'),
        ('writing', '0025_rename_writing_wri_analysi_bbd3b1_idx_writing_wri_analysi_35ea8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf',
            name='feeling_state',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='leaf',
            name='intent_primary',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='leaf',
            name='intent_secondary',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='leaf',
            name='library_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaf',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaf',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='tapestry.place'),
        ),
        migrations.AddField(
            model_name='leaf',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
