# Generated by Django 5.2.8 on 2026-06-24 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('writing', '0026_leaf_feeling_state_leaf_intent_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice')], max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_json', models.JSONField(blank=True, null=True)),
                ('shared', models.BooleanField(default=True)),
                ('audio_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_entry_audio', to='files.storedfile')),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_entry_images', to='files.storedfile')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='writing.leaf')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
