# Generated by Django 5.2.8 on 2026-06-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_leaf_leafentry_leaf_commons_lea_author__758dbb_idx_and_more'),
        ('mindmap', '0002_alter_mindmapnode_leaf'),
        ('writing', '0027_leafentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafplacement',
            name='leaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='commons.leaf'),
        ),
        migrations.RemoveField(
            model_name='leafentry',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='leafentry',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='leafentry',
            name='image_file',
        ),
        migrations.DeleteModel(
            name='Leaf',
        ),
        migrations.DeleteModel(
            name='LeafEntry',
        ),
    ]
