# Generated by Django 5.2.8 on 2026-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0028_alter_leafplacement_leaf_remove_leafentry_leaf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdocument',
            name='bootstrapped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
