# Generated by Django 5.2.8 on 2026-07-14 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('writing', '0029_working_document_bootstrapped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingpiece',
            name='signed_off',
            field=models.BooleanField(db_index=True, default=False, help_text='Set by manual author action; cleared on next body edit.'),
        ),
        migrations.AddField(
            model_name='writingpiece',
            name='spellcheck_clean',
            field=models.BooleanField(db_index=True, default=False, help_text='Set by spellcheck tool on confirmed-clean; cleared on next body edit.'),
        ),
        migrations.CreateModel(
            name='WritingRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('sponsor_object_id', models.UUIDField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sponsor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Writing Run',
                'verbose_name_plural': 'Writing Runs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WritingRunMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_memberships', to='writing.writingpiece')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='writing.writingrun')),
            ],
            options={
                'verbose_name': 'Writing Run Membership',
                'verbose_name_plural': 'Writing Run Memberships',
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='writingrun',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'status'], name='writing_wri_sponsor_c27705_idx'),
        ),
        migrations.AddIndex(
            model_name='writingrun',
            index=models.Index(fields=['status', 'published_at'], name='writing_wri_status_5ca4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='writingrunmembership',
            index=models.Index(fields=['run', 'order_index'], name='writing_wri_run_id_2e3eaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='writingrunmembership',
            unique_together={('run', 'piece')},
        ),
    ]
