# Phase 3 amendment to ADR-0054 (adr-0054-issue-amendment.md):
# rename WritingRun -> Issue, WritingRunMembership -> IssuePlacement,
# WritingRunMembership.run -> IssuePlacement.issue, and add editorial fields.
#
# Hand-written (not autogenerated) to use RenameModel/RenameField instead of
# drop-and-recreate, per the amendment's explicit instruction — this preserves
# any real Phase-1 rows and keeps migration history clean.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0031_writingseries_user_fk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WritingRun',
            new_name='Issue',
        ),
        migrations.RenameModel(
            old_name='WritingRunMembership',
            new_name='IssuePlacement',
        ),
        migrations.RenameField(
            model_name='issueplacement',
            old_name='run',
            new_name='issue',
        ),
        migrations.AlterField(
            model_name='issueplacement',
            name='issue',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='placements',
                to='writing.issue',
            ),
        ),
        migrations.AlterField(
            model_name='issueplacement',
            name='piece',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='issue_placements',
                to='writing.writingpiece',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='issueplacement',
            unique_together={('issue', 'piece')},
        ),
        migrations.RenameIndex(
            model_name='issue',
            old_name='writing_wri_sponsor_c27705_idx',
            new_name='writing_iss_sponsor_e95216_idx',
        ),
        migrations.RenameIndex(
            model_name='issue',
            old_name='writing_wri_status_5ca4d4_idx',
            new_name='writing_iss_status_6969c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='issueplacement',
            name='writing_wri_run_id_2e3eaf_idx',
        ),
        migrations.AddIndex(
            model_name='issueplacement',
            index=models.Index(fields=['issue', 'order_index'], name='writing_iss_issue_i_45c3d9_idx'),
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='issueplacement',
            options={'ordering': ['order_index'], 'verbose_name': 'Issue Placement', 'verbose_name_plural': 'Issue Placements'},
        ),
        migrations.AddField(
            model_name='issue',
            name='designation',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                help_text='Short structural label, e.g. "Issue #1" or "Autumn 2026". Coexists with title.',
            ),
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='TipTap/ProseMirror content — the Issue-native welcome/intro. Does not create a WritingPiece.',
            ),
        ),
        migrations.AddField(
            model_name='issueplacement',
            name='is_lead',
            field=models.BooleanField(
                default=False,
                help_text='Pure metadata for this slice — no functional gating. At most one True per Issue, enforced at the API layer.',
            ),
        ),
    ]
