# Generated by Django 5.2.8 on 2026-09-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0034_writingpiece_signed_off_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdocument',
            name='cursor_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workingdocument',
            name='scroll_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
