# Generated by Django 5.2.8 on 2026-10-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0036_writing_search_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingpiece',
            name='writing_kind',
            field=models.CharField(choices=[('post', 'Post'), ('article', 'Article'), ('dispatch', 'Dispatch'), ('forum', 'Forum Post'), ('announcement', 'Announcement'), ('almanac', 'Almanac'), ('page', 'Page'), ('scene', 'Scene'), ('other', 'Other')], default='post', max_length=20),
        ),
    ]
