# Generated by Django 5.2.8 on 2026-10-06 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('writing', '0037_alter_writingpiece_writing_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('publish', 'Publish')], default='publish', max_length=20)),
                ('target_object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=16)),
                ('state', models.JSONField(blank=True, help_text='Last selection (piece id) and open tool, for exact resume.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Focus',
                'verbose_name_plural': 'Focuses',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'status', '-updated_at'], name='writing_foc_user_id_45d71d_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='writing_foc_target__869fff_idx')],
            },
        ),
    ]
