# /ai/api/urls.py

from django.urls import include, path
from rest_framework.routers import DefaultRouter

# from inkwell.api.views.blacklist import BlacklistedTitleViewSet
# from inkwell.api.views.proto_agent import (
#     ApproveAssetView,
#     DeclineAssetView,
#     DeleteAssetView,
#     IngestedCatalogView,
#     LaunchAgentsView,
#     ListApprovedAssetsView,
#     PreApproveAssetView,
#     RetrieveAllAssetsView,
#     RetrieveAssetsView,
#     SuggestAssetFromUrlView,
#     SuggestAssetsView,
#     SynopsisStatusView,
#     UpdateSuggestedAssetView,
# )
# from inkwell.api.views.views_health_check import health_check, live_check, ready_check

# from .views.views import SimpleRAGView

from inkwell.api.views.llm_proxy import (
    edit_stream_proxy,
    normalize_tiptap_proxy,
    summarize_quick_proxy,
)

# /api/inkwell

router = DefaultRouter()
# router.register("blacklist", BlacklistedTitleViewSet, basename="blacklist")

proto_agent_patterns = [
    # path("pre-approve", PreApproveAssetView.as_view(), name="proto-agent-pre-approve"),
    # path("approve", ApproveAssetView.as_view(), name="proto-agent-approve"),
    # path("approved", ListApprovedAssetsView.as_view(), name="proto-agent-approved"),
    # path("decline", DeclineAssetView.as_view(), name="proto-agent-decline"),
    # path("delete", DeleteAssetView.as_view(), name="proto-agent-delete"),
    # path("suggest-assets", SuggestAssetsView.as_view(), name="proto-agent-suggest-assets"),
    # path("suggestions", SuggestAssetsView.as_view(), name="proto-agent-suggestions"),
    # path("retrieve", RetrieveAssetsView.as_view(), name="proto-agent-retrieve"),
    # path("launch-task", LaunchAgentsView.as_view(), name="proto-agent-launch"),
    # path("retrieve-all", RetrieveAllAssetsView.as_view(), name="proto-agent-retrieve-all"),
    # path("suggestion/<int:pk>", UpdateSuggestedAssetView.as_view(), name="proto-agent-update"),
    # path("suggest-from-url", SuggestAssetFromUrlView.as_view(), name="proto-agent-suggest-from-url"),
    # path("catalog-ingested", IngestedCatalogView.as_view(), name="proto-agent-catalotg-ingested"),

    # path("", include(router.urls)),  # ⬅️ Include all ViewSets (e.g., blacklist) here
]

urlpatterns = [
    # path("health", health_check),
    # path("health/live", live_check),
    # path("health/ready", ready_check),
    # path("ask", SimpleRAGView.as_view(), name="ask"),
    # path("status/synopsis", SynopsisStatusView.as_view(), name="synopsis-status"),
    # path("proto-agent/", include(proto_agent_patterns)),

    path("v1/edit", edit_stream_proxy, name="inkwell-edit"),
    path("v1/normalize-tiptap", normalize_tiptap_proxy, name="inkwell-normalize-tiptap"),
    path("v1/summarize/quick", summarize_quick_proxy, name="inkwell-summarize-quick"),

]




    # path("/proto-agent/suggest-assets", SuggestAssetsView.as_view(), name="proto-agent-suggest"),
    # path("/proto-agent/decline", DeclineAssetView.as_view(), name="proto-agent-decline"),
    # path("/proto-agent/retrieve", RetrieveAssetsView.as_view(), name="proto-agent-retrieve"),
    # path("/proto-agent/launch-task", LaunchAgentsView.as_view(), name="proto-agent-launch"),
    # path("/proto-agent/suggestions", ListSuggestionsView.as_view(), name="proto-agent-suggestions"),
    # path("/proto-agent/approve", ApproveAssetView.as_view(), name="proto-agent-approve"),
    # path("/proto-agent/approved", ListApprovedAssetsView.as_view(), name="proto-agent-approved"),

    # path("/proto-agent/suggestions/{id}/delete", ListApprovedAssetsView.as_view(), name="proto-agent-approved"),

    # path("/proto-agent/retrieve-all", RetrieveAllAssetsView.as_view(), name="proto-agent-retrieve-all"),


    # router.register("blacklist", BlacklistedTitleViewSet, basename="blacklist")



# notes:

# These lines:
# blacklist_list = BlacklistedTitleViewSet.as_view({
#     'get': 'list',
#     'post': 'create'
# })
# blacklist_detail = BlacklistedTitleViewSet.as_view({
#     'get': 'retrieve',
#     'put': 'update',
#     'patch': 'partial_update',
#     'delete': 'destroy'
# })

# urlpatterns += [
#     path('proto-agent/blacklist/', blacklist_list, name='blacklist-list'),
#     path('proto-agent/blacklist/<int:pk>/', blacklist_detail, name='blacklist-detail'),
# ]

# equal this one line:
# router.register("blacklist", BlacklistedTitleViewSet)

# TODO understand that ^^


# and

# Awesome. Here's exactly what gets automatically generated by:

# router.register("blacklist", BlacklistedTitleViewSet, basename="blacklist")

# and mounted at:

# /api/ai/proto-agent/blacklist/

# 📚 DRF Router-Generated Routes
# HTTP Method	URL	Action	Purpose
# GET	/api/ai/proto-agent/blacklist/	list	List all blacklisted titles
# POST	/api/ai/proto-agent/blacklist/	create	Create a new blacklisted title
# GET	/api/ai/proto-agent/blacklist/{id}/	retrieve	Get a specific blacklisted title
# PATCH	/api/ai/proto-agent/blacklist/{id}/	partial_update	Update fields on a blacklisted title
# PUT	/api/ai/proto-agent/blacklist/{id}/	update	Fully update a blacklisted title
# DELETE	/api/ai/proto-agent/blacklist/{id}/	destroy	Delete a blacklisted title
