# Generated by Django 5.2.8 on 2026-02-27 03:57

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0001_initial'),
        ('writing', '0011_leaf_leafcomment_leaf_writing_lea_author__836cc6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('viewport', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('group_read', 'Group Read'), ('explicit_grants', 'Explicit Grants'), ('link_read', 'Link Read')], default='private', max_length=20)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MindMapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('node_type', models.CharField(max_length=32)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('z_index', models.IntegerField(blank=True, null=True)),
                ('collapsed', models.BooleanField(default=False)),
                ('style', models.JSONField(blank=True, null=True)),
                ('backing_kind', models.CharField(choices=[('inline', 'Inline'), ('leaf', 'Leaf')], default='inline', max_length=8)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('primary_url', models.URLField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('leaf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.leaf')),
                ('mind_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='mindmap.mindmap')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MindMapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('edge_type', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('directed', models.BooleanField(default=True)),
                ('style', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('mind_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='mindmap.mindmap')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='mindmap.mindmapnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='mindmap.mindmapnode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MindMapNodeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('kind', models.CharField(choices=[('url', 'Url'), ('image', 'Image'), ('file', 'File'), ('embed', 'Embed'), ('reference', 'Reference')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.storedfile')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mindmap.mindmapnode')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mindmap',
            index=models.Index(fields=['status'], name='mindmap_min_status_e0ff0f_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmap',
            index=models.Index(fields=['-updated_at'], name='mindmap_min_updated_2bcfad_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapnode',
            index=models.Index(fields=['mind_map'], name='mindmap_min_mind_ma_303c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapnode',
            index=models.Index(fields=['mind_map', 'node_type'], name='mindmap_min_mind_ma_6c7f78_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapedge',
            index=models.Index(fields=['mind_map'], name='mindmap_min_mind_ma_a9de51_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapedge',
            index=models.Index(fields=['source_node'], name='mindmap_min_source__87173a_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapedge',
            index=models.Index(fields=['target_node'], name='mindmap_min_target__8668d7_idx'),
        ),
    ]
