# Generated by Django 5.2.8 on 2026-06-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_leaf_leafentry_leaf_commons_lea_author__758dbb_idx_and_more'),
        ('mindmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmapnode',
            name='leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.leaf'),
        ),
    ]
