# Generated by Django 5.2.8 on 2025-11-24 20:22

import django.contrib.postgres.fields
import fundamentals.models
import groups.models.group
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dismissal_type', models.CharField(choices=[('snooze', 'Snoozed for 48 hours'), ('permanent', 'Permanently dismissed')], max_length=16)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('snoozed_until', models.DateTimeField(blank=True, help_text='For snooze type, when to show again', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('persona', 'Persona'), ('circle', 'Circle'), ('community', 'Community'), ('coalition', 'Coalition')], max_length=20)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('background_image', models.CharField(blank=True, max_length=500, null=True)),
                ('background_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('decorators', models.JSONField(blank=True, default=list, help_text='Semantic capability bundles applied to this group (e.g., education_hub, event_venue)')),
                ('additional_permissions', models.JSONField(blank=True, default=list, help_text='Direct permission grants for edge cases (use sparingly)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Main announcement message')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal')], default='normal', help_text='Determines display order in the queue', max_length=16)),
                ('position', models.IntegerField(default=0, help_text='Admin can manually reorder. Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-hide after this datetime', null=True)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('cta_text', models.CharField(blank=True, help_text="Button text like 'View Course', 'RSVP', 'Read More'", max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Link to the content', max_length=500)),
                ('also_send_notification', models.BooleanField(default=False, help_text='If True, also creates Notifications for all group members (use sparingly!)')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique code (e.g., 'isA__Band', 'can__HostEvents')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('capability', 'Capability'), ('policy', 'Policy')], db_index=True, help_text='Category: identity, capability, or policy', max_length=20)),
                ('label', models.CharField(help_text='Human-readable label', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this decorator does')),
                ('valid_for_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Group types this decorator can be applied to (empty = all types)', size=None)),
                ('is_deprecated', models.BooleanField(db_index=True, default=False, help_text="If true, decorator is deprecated and shouldn't be newly assigned")),
                ('version', models.CharField(default='1.0', help_text='Version for tracking decorator changes', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Decorator',
                'verbose_name_plural': 'Group Decorators',
                'db_table': 'groups_groupdecorator',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GroupDecoratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique profile code (e.g., 'profile__Band')", max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable label', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this profile represents')),
                ('valid_for_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Group types this profile can be applied to (empty = all types)', size=None)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If false, profile cannot be applied to new groups')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Decorator Profile',
                'verbose_name_plural': 'Group Decorator Profiles',
                'db_table': 'groups_groupdecoratorprofile',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GroupHasDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='If false, decorator is present but disabled')),
                ('source', models.CharField(choices=[('manual', 'Manual Assignment'), ('profile', 'Applied via Profile'), ('system', 'System Assigned')], default='manual', help_text='How this decorator was assigned', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for temporary decorators', null=True)),
            ],
            options={
                'verbose_name': 'Group Has Decorator',
                'verbose_name_plural': 'Groups Have Decorators',
                'db_table': 'groups_grouphasdecorator',
                'ordering': ['group', 'decorator'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('token', models.CharField(default=groups.models.group.generate_token, max_length=64, unique=True)),
                ('email_status', models.CharField(choices=[('sending', 'Sending invitation'), ('sent', 'Invitation email sent'), ('failed', 'Failed to send invitation')], default='sending', max_length=20)),
                ('invitation_status', models.CharField(choices=[('pending', 'Pending'), ('joined', 'Joined'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('member_object_id', models.UUIDField()),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="List of roles: ['member', 'admin', 'steward', etc.]", size=None)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_pending', models.BooleanField(default=False, help_text='Awaiting acceptance of invitation')),
                ('is_banned', models.BooleanField(default=False, help_text='Banned from group')),
                ('is_evicted', models.BooleanField(default=False, help_text='Removed from group')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('decorators', models.JSONField(blank=True, default=list, help_text='Semantic decorators applied to this membership (e.g., moderator)')),
                ('additional_permissions', models.JSONField(blank=True, default=list, help_text='Direct permission grants for this member (use sparingly)')),
            ],
            options={
                'db_table': 'groups_groupmembership',
            },
        ),
        migrations.CreateModel(
            name='GroupProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, help_text='Order within the profile')),
                ('is_required', models.BooleanField(default=True, help_text='If false, this decorator is optional when applying the profile')),
            ],
            options={
                'db_table': 'groups_groupprofileitem',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=20, unique=True)),
                ('token', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique code (e.g., 'isGroupFounder', 'can__ManageEvents')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('capability', 'Capability'), ('policy', 'Policy')], db_index=True, help_text='Category: identity, permission, or policy', max_length=20)),
                ('label', models.CharField(help_text='Human-readable label', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this decorator grants')),
                ('is_deprecated', models.BooleanField(db_index=True, default=False, help_text="If true, decorator is deprecated and shouldn't be newly assigned")),
                ('version', models.CharField(default='1.0', help_text='Version for tracking decorator changes', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Decorator',
                'verbose_name_plural': 'Membership Decorators',
                'db_table': 'groups_membershipdecorator',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MembershipDecoratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique profile code (e.g., 'profile__Archivist')", max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable label', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this profile represents')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If false, profile cannot be applied to new memberships')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Decorator Profile',
                'verbose_name_plural': 'Membership Decorator Profiles',
                'db_table': 'groups_membershipdecoratorprofile',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MembershipHasDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='If false, decorator is present but disabled')),
                ('source', models.CharField(choices=[('manual', 'Manual Assignment'), ('profile', 'Applied via Profile'), ('system', 'System Assigned')], default='manual', help_text='How this decorator was assigned', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for temporary decorators', null=True)),
            ],
            options={
                'verbose_name': 'Membership Has Decorator',
                'verbose_name_plural': 'Memberships Have Decorators',
                'db_table': 'groups_membershiphasdecorator',
                'ordering': ['membership', 'decorator'],
            },
        ),
        migrations.CreateModel(
            name='MembershipProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, help_text='Order within the profile')),
                ('is_required', models.BooleanField(default=True, help_text='If false, this decorator is optional when applying the profile')),
            ],
            options={
                'db_table': 'groups_membershipprofileitem',
                'ordering': ['sort_order'],
            },
        ),
    ]
