# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementdismissal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_dismissals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CircleGroup',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='circle_detail', serialize=False, to='groups.group')),
                ('start_date', models.DateField(blank=True, help_text='When this circle started', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When this circle ends (if time-bound)', null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of members (optional)', null=True)),
                ('meeting_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('adhoc', 'Ad-Hoc')], default='weekly', help_text='How often the circle meets', max_length=20)),
                ('is_time_bound', models.BooleanField(default=False, help_text='Is this a project circle (time-bound) or ongoing?')),
            ],
            options={
                'verbose_name': 'Circle Group',
                'verbose_name_plural': 'Circle Groups',
                'db_table': 'groups_circlegroup',
            },
        ),
        migrations.CreateModel(
            name='CoalitionGroup',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coalition_detail', serialize=False, to='groups.group')),
                ('governance_model', models.CharField(choices=[('consensus', 'Consensus'), ('majority', 'Majority Vote'), ('representative', 'Representative'), ('delegated', 'Delegated Authority')], default='consensus', help_text='How decisions are made in this coalition', max_length=20)),
                ('charter', models.TextField(blank=True, help_text='Coalition charter or founding document')),
                ('allow_cross_posting', models.BooleanField(default=True, help_text='Allow posts to be shared across member groups')),
                ('shared_resources', models.BooleanField(default=False, help_text='Enable shared resource pools across groups')),
            ],
            options={
                'verbose_name': 'Coalition Group',
                'verbose_name_plural': 'Coalition Groups',
                'db_table': 'groups_coalitiongroup',
            },
        ),
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='community_detail', serialize=False, to='groups.group')),
                ('admission_policy', models.CharField(choices=[('open', 'Open to All'), ('invite_only', 'Invite Only'), ('application', 'Application Required')], default='open', help_text='How new members can join', max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline for the community', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Geographic location (city, region, etc.)', max_length=255)),
            ],
            options={
                'verbose_name': 'Community Group',
                'verbose_name_plural': 'Community Groups',
                'db_table': 'groups_communitygroup',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='sponsor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='group',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupannouncement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupannouncement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupannouncement',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='announcementdismissal',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='groups.groupannouncement'),
        ),
        migrations.AddField(
            model_name='groupdecorator',
            name='conflicts_with',
            field=models.ManyToManyField(blank=True, help_text='Decorators that cannot coexist with this one', to='groups.groupdecorator'),
        ),
        migrations.AddField(
            model_name='groupdecorator',
            name='implies',
            field=models.ManyToManyField(blank=True, help_text='Other decorators this one automatically grants', related_name='implied_by', to='groups.groupdecorator'),
        ),
        migrations.AddField(
            model_name='grouphasdecorator',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_decorators_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouphasdecorator',
            name='decorator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='groups.groupdecorator'),
        ),
        migrations.AddField(
            model_name='grouphasdecorator',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorator_links', to='groups.group'),
        ),
        migrations.AddField(
            model_name='grouphasdecorator',
            name='source_profile',
            field=models.ForeignKey(blank=True, help_text='Profile that assigned this decorator (if source=profile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='groups.groupdecoratorprofile'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='member_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='groupprofileitem',
            name='decorator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_items', to='groups.groupdecorator'),
        ),
        migrations.AddField(
            model_name='groupprofileitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='groups.groupdecoratorprofile'),
        ),
        migrations.AddField(
            model_name='groupdecoratorprofile',
            name='decorators',
            field=models.ManyToManyField(help_text='Decorators included in this profile', related_name='profiles', through='groups.GroupProfileItem', to='groups.groupdecorator'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipdecorator',
            name='conflicts_with',
            field=models.ManyToManyField(blank=True, help_text='Decorators that cannot coexist with this one', to='groups.membershipdecorator'),
        ),
        migrations.AddField(
            model_name='membershipdecorator',
            name='implies',
            field=models.ManyToManyField(blank=True, help_text='Other decorators this one automatically grants', related_name='implied_by', to='groups.membershipdecorator'),
        ),
        migrations.AddField(
            model_name='membershiphasdecorator',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_decorators_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershiphasdecorator',
            name='decorator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_links', to='groups.membershipdecorator'),
        ),
        migrations.AddField(
            model_name='membershiphasdecorator',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorator_links', to='groups.groupmembership'),
        ),
        migrations.AddField(
            model_name='membershiphasdecorator',
            name='source_profile',
            field=models.ForeignKey(blank=True, help_text='Profile that assigned this decorator (if source=profile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='groups.membershipdecoratorprofile'),
        ),
        migrations.AddField(
            model_name='membershipprofileitem',
            name='decorator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_items', to='groups.membershipdecorator'),
        ),
        migrations.AddField(
            model_name='membershipprofileitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='groups.membershipdecoratorprofile'),
        ),
        migrations.AddField(
            model_name='membershipdecoratorprofile',
            name='decorators',
            field=models.ManyToManyField(help_text='Decorators included in this profile', related_name='profiles', through='groups.MembershipProfileItem', to='groups.membershipdecorator'),
        ),
        migrations.CreateModel(
            name='PersonaGroup',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_detail', serialize=False, to='groups.group')),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('friends', 'Friends Only')], default='public', help_text="Who can view this persona's content", max_length=20)),
                ('display_name', models.CharField(blank=True, help_text='Display name (can differ from group title)', max_length=255)),
                ('auto_created_home_circle', models.ForeignKey(blank=True, help_text='Auto-created home circle for this persona', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_homes', to='groups.group')),
                ('user', models.OneToOneField(blank=True, help_text='User this persona belongs to (if 1:1 mapping)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona Group',
                'verbose_name_plural': 'Persona Groups',
                'db_table': 'groups_personagroup',
            },
        ),
        migrations.AddIndex(
            model_name='groupannouncement',
            index=models.Index(fields=['group', 'is_active', 'expires_at'], name='groups_grou_group_i_24b5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='groupannouncement',
            index=models.Index(fields=['group', 'priority', 'position'], name='groups_grou_group_i_da793b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupannouncement',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='groups_grou_source__934d36_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementdismissal',
            index=models.Index(fields=['user', 'dismissal_type'], name='groups_anno_user_id_273a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementdismissal',
            index=models.Index(fields=['snoozed_until'], name='groups_anno_snoozed_b130b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementdismissal',
            unique_together={('announcement', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupdecorator',
            index=models.Index(fields=['category', 'is_deprecated'], name='groups_grou_categor_46966c_idx'),
        ),
        migrations.AddIndex(
            model_name='grouphasdecorator',
            index=models.Index(fields=['group', 'enabled'], name='groups_grou_group_i_26c9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='grouphasdecorator',
            index=models.Index(fields=['decorator', 'enabled'], name='groups_grou_decorat_22cf07_idx'),
        ),
        migrations.AddIndex(
            model_name='grouphasdecorator',
            index=models.Index(fields=['expires_at'], name='groups_grou_expires_b191ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouphasdecorator',
            unique_together={('group', 'decorator')},
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_f7e3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['member_content_type', 'member_object_id'], name='groups_grou_member__d8cfdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'member_content_type', 'member_object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='groupprofileitem',
            unique_together={('profile', 'decorator')},
        ),
        migrations.AddIndex(
            model_name='membershipdecorator',
            index=models.Index(fields=['category', 'is_deprecated'], name='groups_memb_categor_84cd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiphasdecorator',
            index=models.Index(fields=['membership', 'enabled'], name='groups_memb_members_63ac6a_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiphasdecorator',
            index=models.Index(fields=['decorator', 'enabled'], name='groups_memb_decorat_f29416_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiphasdecorator',
            index=models.Index(fields=['expires_at'], name='groups_memb_expires_703878_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershiphasdecorator',
            unique_together={('membership', 'decorator')},
        ),
        migrations.AlterUniqueTogether(
            name='membershipprofileitem',
            unique_together={('profile', 'decorator')},
        ),
    ]
