# Generated by Django 5.2.8 on 2025-11-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
        migrations.RemoveField(
            model_name='group',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='body',
        ),
        migrations.RemoveField(
            model_name='group',
            name='display_layout',
        ),
        migrations.RemoveField(
            model_name='group',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug_history',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug_is_custom',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sponsor_content_type',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sponsor_object_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='group',
            name='summary',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
