# Generated by Django 5.2.8 on 2025-11-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_add_permission_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='groups_group_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupmembership',
            name='groups_membership_active_pending_idx',
        ),
    ]
