# Generated by Django 5.2.8 on 2026-01-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupoverviewlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupoverviewlayout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
