# Generated by Django 5.2.8 on 2026-02-11 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_add_owner_role_and_escrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ADD_OWNER', 'Add Owner'), ('REMOVE_OWNER', 'Remove Owner'), ('DEMOTE_OWNER', 'Demote Owner'), ('TRANSFER_OWNERSHIP', 'Transfer Ownership'), ('SET_ESCROW_OWNER', 'Set Escrow Owner')], max_length=24)),
                ('execute_after', models.DateTimeField(help_text='Request will not execute before this time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of owner state at request time')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests', to='groups.group')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests_targeting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_ownershipchangerequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'execute_after'], name='groups_owne_status_7075cc_idx')],
            },
        ),
    ]
