# Generated by Django 5.2.8 on 2026-04-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_membershiphasdecorator_group_permission_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphasdecorator',
            name='source_group_permission_profile',
            field=models.ForeignKey(blank=True, help_text='Group-owned permission profile that assigned this decorator (if source=profile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decorator_assignments', to='groups.grouppermissionprofile'),
        ),
    ]
