# Generated by Django 5.2.8 on 2026-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_alter_membershiphasdecorator_source_group_permission_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='stackroom_library_id',
            field=models.UUIDField(blank=True, help_text="UUID of this group's Stackroom library. Set when the library is first created.", null=True),
        ),
    ]
