# Generated by Django 5.2.8 on 2026-06-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_add_ispersonabrand_decorator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circles', to='groups.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='visible_to_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('circle', 'Circle'), ('community', 'Community'), ('coalition', 'Coalition')], max_length=20),
        ),
    ]
