# Generated by Django 5.2.8 on 2026-06-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_seed_circle_decorator_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleDeliverableIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('puddlejump_doc', 'Puddlejump Document'), ('dispatch', 'Dispatch'), ('finding', 'Finding')], max_length=20)),
                ('deliverable_status', models.CharField(choices=[('working', 'Working'), ('complete', 'Complete'), ('tabled', 'Tabled')], default='working', max_length=20)),
                ('circle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_intent', to='groups.group')),
            ],
            options={
                'verbose_name': 'Circle Deliverable Intent',
            },
        ),
    ]
