# Generated by Django 5.2.8 on 2026-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_remove_crossroads_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='in_crossroads_commons',
            field=models.BooleanField(default=False, help_text='This group has explicitly opted into the Crossroads public directory. Must default False — every group is standalone until an admin sets this. Defaulting True would opt all existing groups into the commons on migration.'),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
