# Generated by Django 5.2.8 on 2026-08-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_alter_group_in_crossroads_commons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='catalyst_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', help_text='Self-serve Catalyst provisioning state.', max_length=10),
        ),
    ]
