# Generated by Django 5.2.8 on 2026-09-01 19:18

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_migrate_library_contentplacements'),
        ('groups', '0031_add_catalyst_status'),
        ('lanternmail', '0003_alter_welcomeemaildraft_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPublicConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='When True, the public landing page is reachable by anonymous visitors.')),
                ('hero_eyebrow', models.CharField(blank=True, help_text='Orientation label, e.g. "Mindful Brilliance · Crossroads"', max_length=200)),
                ('hero_headline', models.CharField(blank=True, help_text='Point-of-view thesis — not a description', max_length=500)),
                ('hero_body', models.TextField(blank=True, help_text='2–3 sentences of context below the headline')),
                ('hero_primary_cta_label', models.CharField(blank=True, max_length=100)),
                ('hero_primary_cta_action', models.CharField(blank=True, help_text="'scroll:subscribe' | 'scroll:featured' | external URL", max_length=500)),
                ('hero_secondary_cta_label', models.CharField(blank=True, max_length=100)),
                ('hero_secondary_cta_action', models.CharField(blank=True, help_text="'scroll:subscribe' | 'scroll:featured' | external URL", max_length=500)),
                ('featured_item_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Ordered fallback when no collection is set. WritingPiece UUIDs.', size=None)),
                ('featured_content_type', models.CharField(choices=[('writing', 'Writing'), ('documents', 'Documents'), ('mixed', 'Mixed')], default='writing', max_length=20)),
                ('featured_layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20)),
                ('about_text', models.TextField(blank=True, help_text='Short paragraph about the group')),
                ('about_descriptors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="Scannable descriptor list, e.g. ['System architecture', 'AI workflows']", size=None)),
                ('engagement_text', models.TextField(blank=True)),
                ('engagement_capability_pills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('engagement_cta_label', models.CharField(blank=True, max_length=100)),
                ('engagement_cta_action', models.CharField(blank=True, help_text="'email:admin@example.com' | external URL | internal path", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_collection', models.ForeignKey(blank=True, help_text='Preferred source for featured content (Decision 4). Drives ordering and selection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_config_featured', to='curation.collection')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_config', to='groups.group')),
                ('subscription_list', models.ForeignKey(blank=True, help_text='The mailing list public visitors subscribe to. MB list ≠ Crossroads list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_config_subscriptions', to='lanternmail.lanternmaillist')),
            ],
            options={
                'verbose_name': 'Group Public Config',
                'verbose_name_plural': 'Group Public Configs',
            },
        ),
    ]
