# Generated by Django 5.2.8 on 2026-09-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0036_rename_in_crossroads_commons_to_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='in_crossroads_directory',
            field=models.BooleanField(default=False, help_text='This group has explicitly opted into the Crossroads public directory. Must default False — every group is standalone until an admin sets this. Defaulting True would opt all existing groups into the directory on migration.'),
        ),
    ]
