# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0002_opssnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildLogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("commit_hash", models.CharField(db_index=True, max_length=12, unique=True)),
                ("commit_message", models.TextField(blank=True)),
                ("repo", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("work_effort", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Build Log Entry",
                "verbose_name_plural": "Build Log Entries",
                "ordering": ["-date", "-ingested_at"],
            },
        ),
    ]
