# Generated by Django 5.2.8 on 2026-07-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_taskfailurelog'),
        ('ops', '0004_create_cache_table'),
    ]

    operations = [
    ]
