# Generated by Django 5.2.8 on 2026-05-28 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0010_userprofile_intro_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerylState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_surfaced_at', models.DateTimeField(blank=True, null=True)),
                ('last_surfaced_signal', models.CharField(blank=True, max_length=64)),
                ('last_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismiss_mode', models.CharField(choices=[('session', 'Session'), ('permanent', 'Permanent'), ('remind_later', 'Remind Later')], default='session', max_length=32)),
                ('remind_later_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beryl_state', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
