# Generated by Django 5.2.1 on 2025-11-21 21:13

import django.core.validators
import fundamentals.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmblemAvatar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reuse_policy', models.CharField(choices=[('anyone', 'Anyone can attach'), ('owner_only', 'Owner only'), ('public_attr', 'Anyone with attribution')], default='anyone', max_length=16)),
                ('is_unlisted', models.BooleanField(default=False)),
                ('license', models.CharField(choices=[('CC0', 'CC0 (Public Domain)'), ('CC-BY', 'CC BY'), ('CC-BY-SA', 'CC BY-SA'), ('PRO', 'Proprietary')], default='PRO', max_length=16)),
                ('attribution_text', models.CharField(blank=True, default='', max_length=255)),
                ('attribution_url', models.URLField(blank=True, default='')),
                ('image_path', models.CharField(blank=True, max_length=512)),
                ('seed', models.CharField(blank=True, max_length=128)),
                ('style_variant', models.CharField(blank=True, max_length=64)),
                ('fg', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Use #RRGGBB', regex='^#?[0-9A-Fa-f]{6}$')])),
                ('bg', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Use #RRGGBB', regex='^#?[0-9A-Fa-f]{6}$')])),
                ('initials', models.CharField(blank=True, max_length=4)),
                ('palette', models.JSONField(blank=True, default=list)),
                ('size_48', models.CharField(blank=True, max_length=512)),
                ('size_96', models.CharField(blank=True, max_length=512)),
                ('size_192', models.CharField(blank=True, max_length=512)),
                ('size_512', models.CharField(blank=True, max_length=512)),
                ('og_1200x630', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmblemAvatarType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(max_length=32)),
                ('style', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=64)),
                ('is_upload', models.BooleanField(default=False)),
                ('is_generator', models.BooleanField(default=True)),
                ('supports_fg', models.BooleanField(default=True)),
                ('supports_bg', models.BooleanField(default=True)),
                ('supports_initials', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('abstract', 'Abstract'), ('person', 'Person'), ('upload', 'Upload'), ('custom', 'Custom')], default='abstract', max_length=32)),
            ],
        ),
    ]
