# Generated by Django 5.2.1 on 2025-11-21 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emblemavatar',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emblemavatar',
            name='sponsor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='emblemavatar',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emblemavatartype',
            index=models.Index(fields=['engine', 'style'], name='identity_em_engine_d4158c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emblemavatartype',
            unique_together={('engine', 'style')},
        ),
        migrations.AddField(
            model_name='emblemavatar',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emblems', to='identity.emblemavatartype'),
        ),
        migrations.AddIndex(
            model_name='emblemavatar',
            index=models.Index(fields=['type'], name='identity_em_type_id_c66e04_idx'),
        ),
        migrations.AddIndex(
            model_name='emblemavatar',
            index=models.Index(fields=['reuse_policy'], name='identity_em_reuse_p_458925_idx'),
        ),
        migrations.AddIndex(
            model_name='emblemavatar',
            index=models.Index(fields=['license'], name='identity_em_license_a77f97_idx'),
        ),
        migrations.AddIndex(
            model_name='emblemavatar',
            index=models.Index(fields=['is_unlisted'], name='identity_em_is_unli_75a1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='emblemavatar',
            index=models.Index(fields=['seed'], name='identity_em_seed_d85291_idx'),
        ),
        migrations.AddIndex(
            model_name='emblemavatar',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='identity_em_sponsor_334a60_idx'),
        ),
    ]
