# Generated by Django 5.2.8 on 2026-01-26 18:57

import fundamentals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('identity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emblemavatar',
            name='slug',
            field=models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='emblemavatar',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='identity_emblemavatar_slug_sponsor_unique'),
        ),
    ]
