# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fundamentals.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_uid', models.CharField(max_length=128)),
                ('artifact_type', models.CharField(max_length=40)),
                ('format', models.CharField(default='text/plain', max_length=64)),
                ('text', models.TextField(blank=True, null=True)),
                ('storage_key', models.TextField(blank=True, null=True)),
                ('ir_version', models.CharField(default='0.1', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('artifacts_created', models.IntegerField(default=0)),
                ('shards_extracted', models.IntegerField(default=0)),
                ('chunks_indexed', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_hash', models.CharField(help_text='SHA256 hash of query text', max_length=64)),
                ('query_length', models.IntegerField(help_text='Character length of original query')),
                ('limit', models.IntegerField(default=10)),
                ('score_threshold', models.FloatField(blank=True, null=True)),
                ('artifact_types', models.JSONField(blank=True, help_text='List of artifact types filtered', null=True)),
                ('source_file_ids', models.JSONField(blank=True, help_text='List of source file IDs filtered', null=True)),
                ('result_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('embed_ms', models.FloatField(blank=True, help_text='Time to embed query', null=True)),
                ('qdrant_ms', models.FloatField(blank=True, help_text='Time for Qdrant search', null=True)),
                ('resolve_ms', models.FloatField(blank=True, help_text='Time to resolve chunks from Django', null=True)),
                ('total_ms', models.FloatField(blank=True, help_text='Total request time', null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField()),
                ('span', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=20)),
                ('path', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hash_sha256', models.CharField(max_length=64)),
                ('git_commit', models.CharField(blank=True, max_length=64, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('ir_version', models.CharField(default='0.1', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_strategy', models.CharField(default='sliding_window', max_length=40)),
                ('text', models.TextField()),
                ('token_estimate', models.IntegerField(default=0)),
                ('order_index', models.IntegerField()),
                ('source_spans', models.JSONField(default=list)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('ir_version', models.CharField(default='0.1', max_length=32)),
                ('embedding_id', models.CharField(blank=True, default='', max_length=128)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='stackroom.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, help_text='Optional: openai, huggingface, local, etc.', max_length=100)),
                ('dimensions', models.PositiveIntegerField()),
                ('normalize', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_embedding_model_name_version')],
            },
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedded_text_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the exact text that was embedded.', max_length=64)),
                ('qdrant_collection', models.CharField(max_length=200)),
                ('qdrant_point_id', models.CharField(help_text='Point ID in Qdrant (string/uuid).', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='stackroom.chunk')),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunk_embeddings', to='stackroom.embeddingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='stackroom.ingestionrun')),
            ],
        ),
    ]
