# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stackroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='sponsor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='library',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chunkembedding',
            name='library',
            field=models.ForeignKey(help_text='Denormalized from chunk -> artifact -> source_file -> library for isolation guarantees.', on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='stackroom.library'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='stackroom.embeddingmodel'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='stackroom.library'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stackroom_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shard',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shards', to='stackroom.artifact'),
        ),
        migrations.AddField(
            model_name='shard',
            name='parent_shard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stackroom.shard'),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='stackroom.library'),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='stackroom.sourcefile'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='stackroom.sourcefile'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['artifact', 'order_index'], name='stackroom_c_artifac_c1f0a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('artifact', 'chunk_strategy', 'hash_sha256', 'ir_version'), name='uniq_chunk_identity'),
        ),
        migrations.AddIndex(
            model_name='ingestionreceipt',
            index=models.Index(fields=['run', 'created_at'], name='stackroom_i_run_id_20cd45_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='stackroom_l_sponsor_dad1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='stackroom_l_sponsor_686eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['author', '-created_at'], name='stackroom_l_author__db7093_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['submitted_by', '-created_at'], name='stackroom_l_submitt_1e4280_idx'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='stackroom_library_slug_sponsor_unique'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'title'), name='unique_library_title_per_sponsor'),
        ),
        migrations.AddIndex(
            model_name='chunkembedding',
            index=models.Index(fields=['library', 'embedding_model', 'status'], name='idx_ce_lib_model_status'),
        ),
        migrations.AddIndex(
            model_name='chunkembedding',
            index=models.Index(fields=['embedding_model', 'status'], name='idx_ce_model_status'),
        ),
        migrations.AddConstraint(
            model_name='chunkembedding',
            constraint=models.UniqueConstraint(fields=('chunk', 'embedding_model', 'embedded_text_hash'), name='uniq_chunk_embedding_identity'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['library', '-created_at'], name='stackroom_q_library_afb553_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['user', '-created_at'], name='stackroom_q_user_id_936abe_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['embedding_model', '-created_at'], name='stackroom_q_embeddi_78267e_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['-created_at'], name='stackroom_q_created_05e9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='shard',
            index=models.Index(fields=['artifact', 'order_index'], name='stackroom_s_artifac_03e6b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcefile',
            constraint=models.UniqueConstraint(fields=('library', 'hash_sha256'), name='uniq_sourcefile_library_hash'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['source_file', 'artifact_type'], name='stackroom_a_source__8c4858_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('source_file', 'artifact_uid'), name='uniq_artifact_uid_per_source'),
        ),
    ]
