# Generated by Django 5.2.8 on 2026-01-07 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('folder_path', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stackroom.library')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='stackroom.sourcefile')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
                'indexes': [models.Index(fields=['library', 'order_index'], name='stackroom_l_library_615884_idx'), models.Index(fields=['library', 'folder_path'], name='stackroom_l_library_53413f_idx')],
                'constraints': [models.UniqueConstraint(fields=('library', 'source_file', 'order_index'), name='unique_library_item_position')],
            },
        ),
    ]
