# Generated by Django 5.2.8 on 2026-01-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0004_libraryitem_polymorphic'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='libraryitem',
            new_name='stackroom_l_content_760a11_idx',
            old_name='stackroom_l_content_obj_idx',
        ),
    ]
