# Generated by Django 5.2.8 on 2026-01-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stackroom', '0005_rename_stackroom_l_content_obj_idx_stackroom_l_content_760a11_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='libraryitem',
            name='unique_library_item_position',
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='is_folder',
            field=models.BooleanField(default=False, help_text='True if this is an organizational folder, not actual content'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent folder for nesting (max 3 levels)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stackroom.libraryitem'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Folder name (only used when is_folder=True)', max_length=255),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='content_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['library', 'parent'], name='stackroom_l_library_9f576c_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['library', 'is_folder'], name='stackroom_l_library_f0b693_idx'),
        ),
        migrations.AddConstraint(
            model_name='libraryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_folder', False)), fields=('library', 'parent', 'content_type', 'content_object_id', 'order_index'), name='unique_library_item_position'),
        ),
    ]
