# Generated by Django 5.2.8 on 2026-01-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0009_libraryitem_unique_position_root_child'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='library',
            name='stackroom_l_pdl_bundle_idx',
        ),
    ]
