# Generated by Django 5.2.8 on 2026-01-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0010_remove_library_stackroom_l_pdl_bundle_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='interior_summary',
            field=models.TextField(blank=True, default='', help_text='Extractive summary (2-3 sentences from original text, ~300-500 chars) for fast search'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='keywords',
            field=models.JSONField(default=list, help_text='Top 12 keywords extracted via TF-IDF or RAKE (array of strings)'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='metadata_version',
            field=models.CharField(blank=True, default='', help_text='Version of extraction logic used (e.g., "1.0-tfidf" or "1.1-inkwell")', max_length=32),
        ),
    ]
