# Generated by Django 5.2.8 on 2026-01-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0011_artifact_interior_summary_artifact_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_group_puddlejump',
            field=models.BooleanField(db_index=True, default=False, help_text="True if this is a group's canonical archive (one per group)"),
        ),
        migrations.AddField(
            model_name='library',
            name='is_personal_puddlejump',
            field=models.BooleanField(db_index=True, default=False, help_text="True if this is the user's personal canonical archive (one per user)"),
        ),
    ]
