# Generated by Django 5.2.8 on 2026-02-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0012_puddlejump_personal_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='scope',
            field=models.CharField(db_index=True, default='general', help_text='Library scope (e.g., writing, general)', max_length=32),
        ),
        migrations.AddField(
            model_name='library',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Members'), ('unlisted', 'Unlisted'), ('private', 'Private')], db_index=True, default='private', help_text='Visibility of this library', max_length=20),
        ),
    ]
