# Generated by Django 5.2.8 on 2026-02-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0013_library_scope_library_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='flow_mode',
            field=models.CharField(choices=[('sequenced', 'Sequenced'), ('curated', 'Curated'), ('loose', 'Loose')], db_index=True, default='loose', max_length=16),
        ),
    ]
