# Generated by Django 5.2.8 on 2026-02-23 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackroom', '0014_library_flow_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='When the file was checked out', null=True),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, help_text='User who has this file checked out (advisory, not enforced)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='is_canon',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this file has been approved as canonical'),
        ),
        migrations.CreateModel(
            name='SourceFileVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Auto-incremented per source_file')),
                ('hash_sha256', models.CharField(help_text='SHA-256 hash of this version content', max_length=64)),
                ('content_snapshot', models.TextField(help_text='Full markdown content at this version')),
                ('change_summary', models.TextField(blank=True, default='', help_text='Human or auto-generated description of changes')),
                ('ai_assisted', models.BooleanField(default=False, help_text='Whether AI contributed to this version')),
                ('ai_agent', models.CharField(blank=True, default='', help_text='AI agent identifier (e.g. "claude-code", "inkwell")', max_length=64)),
                ('ai_summary', models.TextField(blank=True, default='', help_text='Brief description of what the agent contributed')),
                ('actor', models.ForeignKey(help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_file_versions', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stackroom.sourcefile')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='CanonApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional approval notes')),
                ('approved_by', models.ForeignKey(help_text='User who approved this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canon_approvals', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='stackroom.sourcefile')),
                ('version', models.ForeignKey(help_text='The version being approved as Canon', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='stackroom.sourcefileversion')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='canon_version',
            field=models.ForeignKey(blank=True, help_text='Latest approved Canon version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stackroom.sourcefileversion'),
        ),
        migrations.AddIndex(
            model_name='sourcefileversion',
            index=models.Index(fields=['source_file', 'version_number'], name='stackroom_s_source__b07991_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcefileversion',
            constraint=models.UniqueConstraint(fields=('source_file', 'version_number'), name='uniq_version_per_sourcefile'),
        ),
        migrations.AddIndex(
            model_name='canonapproval',
            index=models.Index(fields=['source_file', '-approved_at'], name='stackroom_c_source__9733c9_idx'),
        ),
    ]
