# Generated by Django 5.2.8 on 2026-04-18 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atelier', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField()),
                ('target_object_id', models.UUIDField()),
                ('verb', models.CharField(choices=[('mentions', 'Mentions'), ('suggests', 'Suggests'), ('recommends', 'Recommends'), ('in_conversation_with', 'In Conversation With'), ('extends', 'Extends'), ('part_of', 'Part Of')], max_length=30)),
                ('status', models.CharField(choices=[('authored', 'Authored'), ('acknowledged', 'Acknowledged'), ('mutual', 'Mutual')], default='authored', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('mutual_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_relations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relations', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id', 'verb')},
            },
        ),
    ]
