# Generated by Django 5.2.8 on 2026-04-21 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0002_artifact_relation'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('writing', '0025_rename_writing_wri_analysi_bbd3b1_idx_writing_wri_analysi_35ea8a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingMarkerOccurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_marker', models.TextField()),
                ('raw_name', models.CharField(max_length=100)),
                ('char_offset', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('affirmed', 'Affirmed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('affirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('sponsor_object_id', models.UUIDField(blank=True, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_occurrences', to='writing.writingpiece')),
                ('sponsor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_marker_occurrences', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['char_offset'],
                'indexes': [models.Index(fields=['piece', 'status'], name='atelier_wri_piece_i_469506_idx'), models.Index(fields=['piece', 'raw_name'], name='atelier_wri_piece_i_d7765b_idx')],
            },
        ),
    ]
