# Generated by Django 5.2.8 on 2026-04-16 03:55

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('members', 'Members'), ('private', 'Private')], default='private', max_length=20)),
                ('scope', models.CharField(choices=[('writing', 'Writing'), ('audio', 'Audio'), ('course', 'Course'), ('general', 'General')], default='general', max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sponsor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('content_object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_folder', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('folder_path', models.CharField(blank=True, max_length=500)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curation.collection')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='curation.collectionitem')),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='curation_co_sponsor_bf94ef_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id', 'slug'], name='curation_co_sponsor_10d895_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['author', '-created_at'], name='curation_co_author__4015b4_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['submitted_by', '-created_at'], name='curation_co_submitt_d471e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('sponsor_content_type', 'sponsor_object_id', 'slug'), name='curation_collection_slug_sponsor_unique'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'order_index'], name='curation_co_collect_aaed6a_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'parent'], name='curation_co_collect_71e2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'is_folder'], name='curation_co_collect_df0b42_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_folder', False), ('parent__isnull', True)), fields=('collection', 'content_type', 'content_object_id', 'order_index'), name='unique_collection_item_position_root'),
        ),
    ]
