# Generated by Django 5.2.8 on 2026-03-25 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workingitem',
            new_name='workbench_w_sponsor_248cd3_idx',
            old_name='workbench_wi_sponsor_idx',
        ),
        migrations.RenameIndex(
            model_name='workingitem',
            new_name='workbench_w_sponsor_ac0d7f_idx',
            old_name='workbench_wi_sponsor_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='workingitem',
            new_name='workbench_w_author__7a3e15_idx',
            old_name='workbench_wi_author_idx',
        ),
        migrations.RenameIndex(
            model_name='workingitem',
            new_name='workbench_w_submitt_e02fc2_idx',
            old_name='workbench_wi_submitted_idx',
        ),
        migrations.RenameIndex(
            model_name='workingitemmembership',
            new_name='workbench_w_piece_c_4ce349_idx',
            old_name='workbench_membership_piece_idx',
        ),
        migrations.AlterField(
            model_name='workingitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workingitem',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
