# Generated by Django 5.2.8 on 2026-01-03 19:17

import django.utils.timezone
import fundamentals.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('commenter', 'Commenter')], default='editor', help_text='Editor can edit, Commenter can only comment', max_length=20)),
            ],
            options={
                'verbose_name': 'Dispatch Collaborator',
                'verbose_name_plural': 'Dispatch Collaborators',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('yjs_document_id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for the Yjs document room', unique=True)),
                ('yjs_state', models.BinaryField(blank=True, help_text='Y.Doc binary encoding for collaborative state (CRDT)', null=True)),
                ('yjs_state_updated_at', models.DateTimeField(blank=True, help_text='Last time yjs state was synced from Socket.IO service', null=True)),
                ('content_snapshot', models.JSONField(blank=True, default=dict, help_text='Last snapshot of TipTap content from Yjs (for offline viewing)')),
                ('snapshot_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Mark as archived to hide from active collaboration')),
                ('last_edited_at', models.DateTimeField(blank=True, help_text='When content was last edited', null=True)),
            ],
            options={
                'verbose_name': 'Dispatch Content (Collaborative Layer)',
                'verbose_name_plural': 'Dispatch Content (Collaborative Layers)',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('content_snapshot', models.JSONField()),
                ('version_note', models.CharField(blank=True, max_length=255)),
                ('is_manual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dispatch Content Version',
                'verbose_name_plural': 'Dispatch Content Versions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dispatch Edit Session',
                'verbose_name_plural': 'Dispatch Edit Sessions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(default='snapshot', help_text="Semantic type: 'snapshot', 'release', 'issue', 'version'", max_length=50)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('yjs_state', models.BinaryField(help_text='Exact collaborative CRDT state for restoration')),
                ('body_json', models.JSONField(help_text='Publishable representation (TipTap/ProseMirror JSON)')),
            ],
            options={
                'verbose_name': 'Dispatch Snapshot',
                'verbose_name_plural': 'Dispatch Snapshots',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64)),
                ('slug_is_custom', models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.')),
                ('slug_history', models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor_object_id', models.UUIDField()),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
