# Generated by Django 5.2.8 on 2025-12-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchcollaborator',
            name='invited_by',
            field=models.ForeignKey(help_text='User who invited this collaborator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchcontent',
            name='collaborators',
            field=models.ManyToManyField(help_text='Users who can collaborate on this content', related_name='dispatch_collaborations', through='dispatch.DispatchCollaborator', through_fields=('content', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchcontent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this collaboration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatch_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchcontent',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last edited content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_dispatch_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchcollaborator',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_assignments', to='dispatch.dispatchcontent'),
        ),
        migrations.AddField(
            model_name='dispatchcontentversion',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dispatch.dispatchcontent'),
        ),
        migrations.AddField(
            model_name='dispatchcontentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatcheditsession',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='dispatch.dispatchcontent'),
        ),
        migrations.AddField(
            model_name='dispatcheditsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='post',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispatchcontent',
            index=models.Index(fields=['yjs_document_id'], name='dispatch_di_yjs_doc_e66eee_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchcontent',
            index=models.Index(fields=['is_archived'], name='dispatch_di_is_arch_e6fb30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dispatchcollaborator',
            unique_together={('content', 'user')},
        ),
    ]
