# Generated by Django 5.2.8 on 2026-02-19 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_initial'),
        ('writing', '0005_writingpiece_enable_outline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOutlineNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('anchor_target', models.UUIDField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dispatch.dispatchoutlinenode')),
                ('writing_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_nodes', to='writing.writingpiece')),
            ],
            options={
                'ordering': ['writing_piece_id', 'parent_id', 'order_index', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['writing_piece'], name='dispatch_di_writing_c7f1b8_idx'), models.Index(fields=['parent'], name='dispatch_di_parent__cfe519_idx'), models.Index(fields=['anchor_target'], name='dispatch_di_anchor__d377fd_idx'), models.Index(fields=['writing_piece', 'parent', 'order_index'], name='dispatch_di_writing_8af2cd_idx')],
            },
        ),
    ]
