# Generated by Django 5.2.8 on 2025-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdocument',
            name='yjs_state',
            field=models.BinaryField(blank=True, help_text='Y.Doc binary encoding for collaborative state (CRDT)', null=True),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='yjs_state_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time yjs state was synced from Socket.IO service', null=True),
        ),
    ]
