# Generated by Django 5.2.8 on 2026-07-24 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_dispatchoutlinenode'),
        ('writing', '0030_writing_assembly_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('block_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('anchor_from', models.IntegerField(blank=True, null=True)),
                ('anchor_to', models.IntegerField(blank=True, null=True)),
                ('quoted_text', models.CharField(blank=True, max_length=512)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_comments_authored', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dispatch.dispatchcomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_comments_resolved', to=settings.AUTH_USER_MODEL)),
                ('writing_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_comments', to='writing.writingpiece')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['writing_piece', 'parent'], name='dispatch_di_writing_1a10f6_idx')],
            },
        ),
    ]
