# Generated by Django 5.2.8 on 2025-12-05 21:40

import django.db.models.deletion
import fundamentals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dispatch', '0003_dispatchdocument_yjs_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchdocument',
            options={'verbose_name': 'Dispatch Document', 'verbose_name_plural': 'Dispatch Documents'},
        ),
        migrations.RemoveField(
            model_name='dispatchdocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dispatchdocument',
            name='is_published',
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='slug_history',
            field=models.JSONField(blank=True, default=list, help_text='Previous slugs for optional redirects (leave empty for now).'),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='slug_is_custom',
            field=models.BooleanField(default=False, help_text='If True, the slug will not auto-regenerate from title.'),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='sponsor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='sponsor_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchdocument',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispatchdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dispatchdocument',
            name='slug',
            field=models.SlugField(default=fundamentals.models.default_slug, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='dispatchdocument',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='dispatchdocument',
            index=models.Index(fields=['sponsor_content_type', 'sponsor_object_id'], name='dispatch_di_sponsor_21ca2b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchdocument',
            index=models.Index(fields=['author', '-created_at'], name='dispatch_di_author__b49e56_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchdocument',
            index=models.Index(fields=['submitted_by', '-created_at'], name='dispatch_di_submitt_8b3e05_idx'),
        ),
    ]
