# Generated by Django 5.2.8 on 2026-09-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_dispatch_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchsnapshot',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
