# Generated by Django 5.2.8 on 2026-05-07 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0015_stackroom_library_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubCapture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('fix', "Let's Fix"), ('need_more', 'We Need More'), ('remind', 'Remind Me'), ('note', 'Note')], max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('promoted', 'Promoted')], default='open', max_length=20)),
                ('promoted_to_object_id', models.UUIDField(blank=True, null=True)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_captures', to='groups.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_captures', to=settings.AUTH_USER_MODEL)),
                ('promoted_to_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['owner', 'status', 'kind'], name='console_hub_owner_i_1ffa98_idx'), models.Index(fields=['group', 'status', 'kind'], name='console_hub_group_i_a6964c_idx'), models.Index(fields=['owner', '-created_at'], name='console_hub_owner_i_fd5138_idx'), models.Index(fields=['remind_at'], name='console_hub_remind__c6f4b7_idx')],
            },
        ),
    ]
