# Generated by Django 5.2.8 on 2026-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_agentpersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubcapture',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='agentpersona',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
