# Generated by Django 5.2.8 on 2026-05-28 03:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('initiatives', '0016_alter_actionrun_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_object_id', models.UUIDField()),
                ('body', models.TextField()),
                ('intent_tag', models.CharField(choices=[('reminder', 'Reminder'), ('recipe', 'Recipe'), ('contact', 'Contact'), ('reference', 'Reference'), ('list', 'List'), ('idea', 'Idea'), ('link', 'Link'), ('question', 'Question'), ('note', 'Note')], default='note', max_length=32)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Max 10 labels, 64 chars each.', size=None)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('remind_recurrence', models.CharField(blank=True, max_length=32)),
                ('remind_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], max_length=16, null=True)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('reviewed', 'Reviewed'), ('promoted', 'Promoted'), ('archived', 'Archived')], default='raw', max_length=16)),
                ('promoted_to_object_id', models.UUIDField(blank=True, null=True)),
                ('intent_tag_misfit', models.BooleanField(default=False)),
                ('intent_tag_misfit_note', models.CharField(blank=True, max_length=255)),
                ('aperture_log_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraps', to='initiatives.aperturelogentry')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraps', to='initiatives.initiative')),
                ('promoted_to_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_scraps', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['intent_tag'], name='scrap_scrap_intent__a66e07_idx'), models.Index(fields=['status'], name='scrap_scrap_status_4cb29e_idx'), models.Index(fields=['content_type', 'owner_object_id', 'status'], name='scrap_scrap_content_aa14f5_idx'), models.Index(fields=['remind_at', 'remind_status'], name='scrap_scrap_remind__00b1a1_idx')],
            },
        ),
    ]
